Content
vishvAsa/vedAH_yajuH pull request #106
Opened 2022-12-14 05:28 UTC by ramamurthy-s

पङ्क्त्यः १ - ६१ पर्यन्तं परिष्कृतवान् ।

2022-12-28 03:38 UTC, vvasuki requested changes

2022-12-28 03:38 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/06_pitRmedhaprayogaH.md
> +( अनुशंसनकमः )
इयम् पङ्क्तिर् भिन्न-paragraph-मध्ये भवतु।

2022-12-28 04:56 UTC, ramamurthy-s commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/06_pitRmedhaprayogaH.md
> +( अनुशंसनकमः )
परिष्कृतम् ।

2023-01-05 08:02 UTC, vvasuki requested changes

2023-01-05 08:02 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/06_pitRmedhaprayogaH.md
> +इति । तत्र दक्षिणाग्रान दर्भान् संस्तीर्य तेषु दक्षिणाग्रैर्याज्ञिकैः काष्ठैश्चितां कल्पयित्वा तत्र दक्षिणाग्रीवमधरलोम कृष्णाजिनमास्तीर्य दक्षिणाशिरसमुत्तानं प्रतं निधायाऽपकृष्य रज्जुमासन्दीमपविध्य च
अत्र दीर्घ आवरणस्थपाठो विद्यते। (प्रेतस्य भार्यामुपसंवेशयति … भार्योपसंवेशनमुत्थापनञ्च नानुष्टेयम्, कलौ निषिद्धत्वात् ॥) इति 

स भिन्ने पाठखण्डे स्थापनीयः। एवं सर्वत्र दीर्घेष्व् आवरणगतेषु पाठेषु।

2023-01-05 09:19 UTC, ramamurthy-s commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/06_pitRmedhaprayogaH.md
> +इति । तत्र दक्षिणाग्रान दर्भान् संस्तीर्य तेषु दक्षिणाग्रैर्याज्ञिकैः काष्ठैश्चितां कल्पयित्वा तत्र दक्षिणाग्रीवमधरलोम कृष्णाजिनमास्तीर्य दक्षिणाशिरसमुत्तानं प्रतं निधायाऽपकृष्य रज्जुमासन्दीमपविध्य च
![image](https://user-images.githubusercontent.com/119562004/210743566-2fa04135-683e-417f-a7ce-7372e574d5fb.png)

मम अवगमनम् एतत् अस्ति । कृपया सूचयन्तु एतत् समीचीनम् ।
भिन्न पाराग्राफ् मध्ये  (प्रेतस्य भार्यामुपसंवेशयति … भार्योपसंवेशनमुत्थापनञ्च नानुष्टेयम्, कलौ निषिद्धत्वात् ॥) स्थापनीयम् ।
किन्तु ᳚प्रेतं पात्राणि चिताञ्च प्रोक्ष्याऽऽज्यसंस्कारादि स्रुक्सम्मार्जनान्तं कृत्वा स्रुचि चतुर्गृहीतं गृहीत्वा व्याहृतीविंग्राहं हुत्वा ᳚ इत्यत्र पूर्णबिन्दुः नास्ति । कथम् एतत् करणीयम् ।

2023-01-05 09:30 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/06_pitRmedhaprayogaH.md
> +इति । तत्र दक्षिणाग्रान दर्भान् संस्तीर्य तेषु दक्षिणाग्रैर्याज्ञिकैः काष्ठैश्चितां कल्पयित्वा तत्र दक्षिणाग्रीवमधरलोम कृष्णाजिनमास्तीर्य दक्षिणाशिरसमुत्तानं प्रतं निधायाऽपकृष्य रज्जुमासन्दीमपविध्य च
नमामि। `हत्वा` इत्यस्मात् परं पूर्णविरामो नास्ति चेद् अपि +आवरणस्थपाट्ःओ भिन्न-पाथखण्डे ऽस्तु। नाम, `(`चिह्नात् पूर्वं रिक्तां पङ्क्तिं स्थापयतु।

2023-01-05 12:35 UTC, ramamurthy-s commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/06_pitRmedhaprayogaH.md
> +इति । तत्र दक्षिणाग्रान दर्भान् संस्तीर्य तेषु दक्षिणाग्रैर्याज्ञिकैः काष्ठैश्चितां कल्पयित्वा तत्र दक्षिणाग्रीवमधरलोम कृष्णाजिनमास्तीर्य दक्षिणाशिरसमुत्तानं प्रतं निधायाऽपकृष्य रज्जुमासन्दीमपविध्य च
![Uploading image.png…]()
एतत् समीचीनम् वा ।

2023-01-05 12:36 UTC, ramamurthy-s commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/06_pitRmedhaprayogaH.md
> +इति । तत्र दक्षिणाग्रान दर्भान् संस्तीर्य तेषु दक्षिणाग्रैर्याज्ञिकैः काष्ठैश्चितां कल्पयित्वा तत्र दक्षिणाग्रीवमधरलोम कृष्णाजिनमास्तीर्य दक्षिणाशिरसमुत्तानं प्रतं निधायाऽपकृष्य रज्जुमासन्दीमपविध्य च
![image](https://user-images.githubusercontent.com/119562004/210781686-d4f76048-7b05-4ada-b52d-56e635c37c42.png)
एतत् समीचीनम् वा ।

2023-01-05 14:14 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/06_pitRmedhaprayogaH.md
> +इति । तत्र दक्षिणाग्रान दर्भान् संस्तीर्य तेषु दक्षिणाग्रैर्याज्ञिकैः काष्ठैश्चितां कल्पयित्वा तत्र दक्षिणाग्रीवमधरलोम कृष्णाजिनमास्तीर्य दक्षिणाशिरसमुत्तानं प्रतं निधायाऽपकृष्य रज्जुमासन्दीमपविध्य च
आम्

2023-01-05 16:55 UTC, ramamurthy-s commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/06_pitRmedhaprayogaH.md
> +इति । तत्र दक्षिणाग्रान दर्भान् संस्तीर्य तेषु दक्षिणाग्रैर्याज्ञिकैः काष्ठैश्चितां कल्पयित्वा तत्र दक्षिणाग्रीवमधरलोम कृष्णाजिनमास्तीर्य दक्षिणाशिरसमुत्तानं प्रतं निधायाऽपकृष्य रज्जुमासन्दीमपविध्य च
परिष्कृतम् ।

2023-01-05 16:57 UTC, merged