शिथिलीकल्प:‍ शोधित्वा प्रेषितम्
vishvAsa/vedAH_yajuH pull request #112
Opened 2022-12-19 16:06 UTC by Malamanian

2022-12-19 16:07 UTC, vvasuki requested changes

2022-12-19 16:07 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/14_shatAbhiShekavidhiH_sahasrachandradarshanashAnt.md
> +प्राप्ते शततमे वर्षे अपमृत्युभवेध्रुवम् ।
उद्धरणचिह्नानि न दृश्यन्त एव??

2022-12-19 16:33 UTC, Malamanian commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/14_shatAbhiShekavidhiH_sahasrachandradarshanashAnt.md
> +प्राप्ते शततमे वर्षे अपमृत्युभवेध्रुवम् ।
उद्धरणचिह्नं कृतवान्

2022-12-20 11:03 UTC, Malamanian commented
पुन: संवीक्ष्य यत्र यत्र उद्धरण चिह्नानि (>) अवेक्षितं स्थापयित्वा
प्रेषितवान्

On Tue, 20 Dec 2022 at 09:57, Vishvas Vasuki विश्वासः <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/14_shatAbhiShekavidhiH_sahasrachandradarshanashAnt.md
> <https://github.com/vishvAsa/vedAH_yajuH/pull/112#discussion_r1052895592>:
>
> > +
> +इति प्रधानकलशशषेणाऽभिषिञ्चति ।
> +
> +अहतानि वासांसि परिधायाप आचम्यालङ्कृत्य तत आदित्यमुदीक्षयति-
> +
> +'उद्वयं तमसस्परि, उदु त्यं, चित्रं, तच्क्षुर्देवहितं, य उदगात'
> +
> +इति ॥
> +
> +'अथैतेनैव यथेतमेत्यैरकां साधिवासामास्तीर्य तस्यां प्राङ्मुख उपवेश्य सुवर्णरजतताम्रकांस्ये वा पात्रे हविराज्यं हिरण्यं निधाय निमील्यावेक्ष्य ब्राह्मणाय प्रयच्छति ॥ अथ रथमारुह्य ग्रामं प्रदक्षिणीकृत्य दुन्दुभिशब्देन स्वस्तिसूक्तेन गृहं प्रविश्य गुरवे वरं दत्वा ब्राह्मणान् सम्पूज्याशिषो वाचयित्वा दशपूर्वान्दशापरानात्मानञ्चैकविंशतिं पक्तिं च पुनाति पुत्रपौत्रैश्च षष्टिवर्षसहस्राणि स्वर्गलोकमतीत्य ब्रह्मणस्सायुज्यं सलोकतामाप्नोति'
> +
> +इत्याह भगवान बोधायनः ॥
> +
> +शौनकः-
> +
> +प्राप्ते शततमे वर्षे अपमृत्युभवेध्रुवम् ।
>
> बहुत्र स एव दोषः। सम्यक् परीक्ष्य परिष्कृत्य सूचयतु।
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/vishvAsa/vedAH_yajuH/pull/112#discussion_r1052895592>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4FR6DTLCXG5TUCSUWDCI7TWOEYRTANCNFSM6AAAAAATDQXLAQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-20 11:58 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/14_shatAbhiShekavidhiH_sahasrachandradarshanashAnt.md
> +प्राप्ते शततमे वर्षे अपमृत्युभवेध्रुवम् ।
अपेक्षितस्थानेषु प्रतिसूत्रं यथाशिक्षितम् उत्तराणि लेख्यानि।

2022-12-21 04:48 UTC, Malamanian commented
पुन: संवीक्ष्य यत्र यत्र उद्धरण चिह्नानि (>) अवेक्षितं स्थापयित्वा
प्रेषितवान्

2022-12-21 05:22 UTC, Malamanian commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/14_shatAbhiShekavidhiH_sahasrachandradarshanashAnt.md
> +प्राप्ते शततमे वर्षे अपमृत्युभवेध्रुवम् ।
शताभिषेकविधि मद्ये सर्वत्र उद्धरण चिह्नानि स्थापितवान्

2022-12-21 05:23 UTC, Malamanian commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/14_shatAbhiShekavidhiH_sahasrachandradarshanashAnt.md
> +एते चाऽन्ये महोत्याता जायन्ते नात्रसंशयः ॥ ४ ॥    तदाऽनिष्टनिवृत्त्यर्थं क्षेमायुष्यविवृद्धये ।
पङ्तिविभेद: कृतम्

2022-12-21 05:30 UTC, merged