37पंक्ति पर्यन्तं शोधनं
vishvAsa/vedAH_yajuH pull request #113
Opened 2022-12-19 16:31 UTC by ramjay15

३७ पंक्ति पर्यन्तं शोधनं कृत्वा समर्पयामि।

2022-12-22 07:39 UTC, vvasuki requested changes

2022-12-22 07:39 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +>  ᳚पितृभ्यो वो जुष्टं निर्वपामि”
आदौ वर्तमानम्  ᳚ iti चिह्नं न समीचीणम्।

2022-12-22 07:39 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +पिण्डपितृयज्ञविधिः॥ (वो.गृ.प.सू.१.१६.१२-१३)अथामावास्यायां प्रसिद्धः पिण्डपितृयज्ञः॥ नात्र गार्हपत्यशब्दो विद्यते॥
`बो‌. गृ` इति स्यात्।

2022-12-22 07:39 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +इति]
किमत्र ]-चिह्नम्?

2022-12-22 07:39 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +इति]
अन्ते ]-चिह्नम्?

2022-12-22 15:56 UTC, ramjay15 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +पिण्डपितृयज्ञविधिः॥ (वो.गृ.प.सू.१.१६.१२-१३)अथामावास्यायां प्रसिद्धः पिण्डपितृयज्ञः॥ नात्र गार्हपत्यशब्दो विद्यते॥
यतोक्तं कृतवान्।

2022-12-22 16:04 UTC, ramjay15 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +>  ᳚पितृभ्यो वो जुष्टं निर्वपामि”
समीचीणम् " चिह्न्ं  स्थपितवान्।

2022-12-22 16:15 UTC, ramjay15 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +इति]
१७तमे पङ्क्तौ आदौ "[" चिह्न्ं अस्ति,३७ तमे अन्ते "]" चिह्न्ं आसीत्।

2022-12-22 16:23 UTC, ramjay15 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +इति]
६५पङ्क्तौ आदौ "["चिह्नं अस्ति। ७९पङ्क्तौ अवसान चिह्नं "]" स्थितम्।

2022-12-23 02:18 UTC, vvasuki requested changes

2022-12-23 02:18 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +पिण्डपितृयज्ञविधिः॥ (बो.गृ.प.सू.१.१६.१२-१३)अथामावास्यायां प्रसिद्धः पिण्डपितृयज्ञः॥ नात्र गार्हपत्यशब्दो विद्यते॥
अथामावास्यायां प्रसिद्धः पिण्डपितृयज्ञः॥ नात्र गार्हपत्यशब्दो विद्यते॥ 

इत्येतावद् (बो.गृ.प.सू.१.१६.१२-१३) इत्यस्माद् उद्धरणम्। तदनुसारेण पङ्क्तीर् एवं रचयेत् -

```
(बो.गृ.प.सू.१.१६.१२-१३) 

> अथामावास्यायां प्रसिद्धः पिण्डपितृयज्ञः॥ नात्र गार्हपत्यशब्दो विद्यते॥ 
```

2022-12-23 02:18 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +> (बौधायनश्रौ॰ ३.१०-११,२०.२१;२४,३२)
एतद् उद्धरणाङ्गं न। उद्धरणचिह्नं निष्कासयतु। अत्रारभ्यान्तम् पूर्णं बौधायनश्रौतसूत्राद् उद्धृतम्। तच्च व्याख्यानेन सह प्रस्तुतम्। 
अतः अग्रिमानि वाक्यानि यद्यपि श्रौतसूत्रेभ्य उद्धृतानि, अधिकम् उद्धरणचिह्नं विना प्रस्तोष्यते।

2022-12-23 02:18 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +> 'पिण्डपितृयज्ञं करिष्यन्नुपकल्पयते'
`'` इति निष्कासयतु। अत्र तु अन्ते मूले पादटिप्पनीसङ्केतो विद्यते। पादटिप्पन्यो रक्षणीयाः https://sanskrit.github.io/groups/dyuganga/projects/text/proofreading/editing/markdown/ इत्यत्रोक्तया रीत्या।

उद्धरणचिह्नम् अपि निष्कासयतु।

2022-12-23 02:18 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +> '[पिण्डपितृयज्ञस्य करण'
यत्र यत्र `[]` इति दीर्घपाठो विद्यते, तत्र तत्र तस्मिन्न् वर्तमानम् पाठम् एवं रक्षतु - 

```
<details><summary>टीका</summary>

'पिण्डपितृयज्ञस्य करण' इति॥ ….
....
> 'शालीकिरादित एव प्राचीनावीतं कुर्वीत। स प्राचीनावीत्येव स्याद् आ प्राजापत्यायै। यज्ञोपवीत्येव प्राजापत्ययचोर्ड्डेन्यात्' 

इति। 
</details>
```

एवं सर्वत्र करणीयम्।

2022-12-24 14:56 UTC, ramjay15 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +> 'पिण्डपितृयज्ञं करिष्यन्नुपकल्पयते'
यथा भवता उक्तम् " निष्कासितम्। पादटिप्पन्यो रक्षितवान्।

2022-12-24 15:04 UTC, ramjay15 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +पिण्डपितृयज्ञविधिः॥ (बो.गृ.प.सू.१.१६.१२-१३)अथामावास्यायां प्रसिद्धः पिण्डपितृयज्ञः॥ नात्र गार्हपत्यशब्दो विद्यते॥
यथा उक्तम्  उद्धरणम् कृतवान्।

2022-12-24 15:10 UTC, ramjay15 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +> (बौधायनश्रौ॰ ३.१०-११,२०.२१;२४,३२)
उद्धरणचिह्नं निष्कासितम्।

2022-12-25 04:02 UTC, ramjay15 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +> '[पिण्डपितृयज्ञस्य करण'
यथा उक्तं वर्तमानम् पाठम्  रक्षितवान्।

2022-12-25 04:32 UTC, ramjay15 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> -1014
पृष्टसङ्ख्या [[१०१४] रक्षितवान्।

2022-12-25 04:37 UTC, ramjay15 commented
नमस्ते।यथा उक्तं कृत्वा प्रेषितवान्।

On Fri, Dec 23, 2022 at 7:48 AM Vishvas Vasuki विश्वासः <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In
> taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> <https://github.com/vishvAsa/vedAH_yajuH/pull/113#discussion_r1055975018>:
>
> >
> -1014
>
> पृष्ठसङ्ख्या रक्षणीया। [[1014]] इति रक्षतु।
> ------------------------------
>
> In
> taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> <https://github.com/vishvAsa/vedAH_yajuH/pull/113#discussion_r1055976020>:
>
> >
> -१. यजमानः
>
> इमां पादटिप्पनीं किं कृतवान्?? पादटिप्पन्यो रक्षणीयाः
> https://sanskrit.github.io/groups/dyuganga/projects/text/proofreading/editing/markdown/
> इत्यत्रोक्तया रीत्या। सुब्रह्मण्यार्यायापि सूचयतु।
> ------------------------------
>
> In
> taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> <https://github.com/vishvAsa/vedAH_yajuH/pull/113#discussion_r1055982998>:
>
> > @@ -2,21 +2,90 @@
>  title = "५२ पिण्डपितृयज्ञविधिः"
>
>  +++
> -पिण्डपितृयज्ञविधिः ॥ ___ (वो. गृ. प. सू. १. १६. १२-१३) अथामावास्यायां प्रसिद्धः पिण्डपितृयज्ञः ॥ नात्र गार्हपत्यशब्दो विद्यते ॥ 2 (बौधायनश्रौ० ३. १०-११, २०. २१; २४. ३२) पिण्डपितृयज्ञं करिष्यन्नुपकल्पयते' सकृदाच्छिन्नं बहिर्दर्भारश्च परिस्त
> +पिण्डपितृयज्ञविधिः॥ (बो.गृ.प.सू.१.१६.१२-१३)अथामावास्यायां प्रसिद्धः पिण्डपितृयज्ञः॥ नात्र गार्हपत्यशब्दो विद्यते॥
>
> अथामावास्यायां प्रसिद्धः पिण्डपितृयज्ञः॥ नात्र गार्हपत्यशब्दो विद्यते॥
>
> इत्येतावद् (बो.गृ.प.सू.१.१६.१२-१३) इत्यस्माद् उद्धरणम्। तदनुसारेण
> पङ्क्तीर् एवं रचयेत् -
>
> (बो.गृ.प.सू.१.१६.१२-१३)
>
> > अथामावास्यायां प्रसिद्धः पिण्डपितृयज्ञः॥ नात्र गार्हपत्यशब्दो विद्यते॥
>
> ------------------------------
>
> In
> taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> <https://github.com/vishvAsa/vedAH_yajuH/pull/113#discussion_r1055983828>:
>
> >
> -रणीयान् व्रीहीश्च शूर्प च प्रक्षालिते चोलूखलमुसले स्थाली सस्रुवा समेक्षणामेरकोपर्वहणे आअनाभ्याने दशा स्फ्य मुदकुम्भं यज्ञायुधानाति । अथाऽन्याहार्यपचनं परिस्तृणाति । तमुत्तरेणैकैक सरसादयति एरकोपबर्हणे आञ्जनाभ्यञ्जने दशा स्फ्यमुदकुम्भं यज्ञायुधानीति। अथ प्राचीनावीतं कृत्वा जघनेनाऽन्वाहार्यपचनमुपविश्य पवित्रवत्या स्थाल्यां ब्रीहीनिर्वपति "पितृभ्यो वो जुष्टं निर्वपामि” इति वा तूष्णीं वा। [ पिण्डपितृयज्ञस्य करण इति ॥ सह स्माऽऽ ह बौधायन आदित एव प्राचीनावी कुति । स प्राचीनावीत्येव स्याद आ आहुतीना होमात् । आहुतीझैष्यन् यज्ञोपवीतं कुर्वीत । स यज्ञोपवीत्येव स्याद् आ सकृदा च्छिन्नस्य स्तरणात् । सकृदाच्छिन्न५ स्तरिष्यन् प्राचीनावीतं कुर्वीत । स प्राचीनावीत्येव स्याद् आ प्राजापत्यायै । यज्ञो
> +> (बौधायनश्रौ॰ ३.१०-११,२०.२१;२४,३२)
>
> एतद् उद्धरणाङ्गं न। उद्धरणचिह्नं निष्कासयतु। अत्रारभ्यान्तम् पूर्णं
> बौधायनश्रौतसूत्राद् उद्धृतम्। तच्च व्याख्यानेन सह प्रस्तुतम्।
> अतः अग्रिमानि वाक्यानि यद्यपि श्रौतसूत्रेभ्य उद्धृतानि, अधिकम्
> उद्धरणचिह्नं विना प्रस्तोष्यते।
> ------------------------------
>
> In
> taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> <https://github.com/vishvAsa/vedAH_yajuH/pull/113#discussion_r1055984129>:
>
> >
> -पवीत्येव प्राजापत्ययर्चा गार्हपत्यमुपतिष्ठतेति । अत्रो ह स्माऽऽह शालीकिरादित एव प्राचीनावीतं कुर्वीत । स प्राचीना Mal वीत्येव स्याइ आ प्राजापत्यायै । यज्ञोपवीत्येव प्राजापत्ययर्बोदडेन्यादिति ॥] उपर्यर्धा स्थालीं कृत्वैतस्मिन्नेव चर्मण्युलूखल | मुसले निधायाऽवहन्ति सकृदेव दाक्षिणामुखः। अथैनानविविच्य । अथैतस्यामेव स्थाल्यां तिर पवित्रमप आनीयाऽधिश्रित्य तिरः पवित्रं तण्डुलानावपति। [तूष्णी सकृदुत्पूय सकृत्प्रोक्ष्य सकृद्धविष्कृढूपं कुर्यादिति बौधायनः ॥ सकृदेवैनान सुफलीकृतान कृत्वा
> +> 'पिण्डपितृयज्ञं करिष्यन्नुपकल्पयते'
>
> ' इति निष्कासयतु। अत्र तु अन्ते मूले पादटिप्पनीसङ्केतो विद्यते।
> पादटिप्पन्यो रक्षणीयाः
> https://sanskrit.github.io/groups/dyuganga/projects/text/proofreading/editing/markdown/
> इत्यत्रोक्तया रीत्या।
>
> उद्धरणचिह्नम् अपि निष्कासयतु।
> ------------------------------
>
> In
> taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> <https://github.com/vishvAsa/vedAH_yajuH/pull/113#discussion_r1055988128>:
>
> >
> -1014
> +> '[पिण्डपितृयज्ञस्य करण'
>
> यत्र यत्र [] इति दीर्घपाठो विद्यते, तत्र तत्र तस्मिन्न् वर्तमानम् पाठम्
> एवं रक्षतु -
>
> <details><summary>टीका</summary>
>
> 'पिण्डपितृयज्ञस्य करण' इति॥ ….
> ....
> > 'शालीकिरादित एव प्राचीनावीतं कुर्वीत। स प्राचीनावीत्येव स्याद् आ प्राजापत्यायै। यज्ञोपवीत्येव प्राजापत्ययचोर्ड्डेन्यात्'
>
> इति।
> </details>
>
> एवं सर्वत्र करणीयम्।
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/vishvAsa/vedAH_yajuH/pull/113#pullrequestreview-1228444160>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4IHOFNNUSFWX6PX24GHTXLWOUDW7ANCNFSM6AAAAAATDRQ5JE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-25 05:22 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> -1014
रक्षितं न दृश्यत एव।

2022-12-25 05:22 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +[^१] यजमानः
पादटिप्पनीविन्यासः सम्यङ् नास्ति। पुनः https://sanskrit.github.io/groups/dyuganga/projects/text/proofreading/editing/markdown/  इति पश्यतु। रिक्तपङ्क्ती, :-चिह्नं च न दृश्यन्ते।

2022-12-25 05:22 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +> '[पिण्डपितृयज्ञस्य करण'
न रक्षितवान्। अन्यथा कुतः `<details> …` इत्यादिकं न दृश्यते?

2022-12-25 06:06 UTC, ramjay15 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +[^१] यजमानः
अवगतम्। समीचीनम् कृतवान्।

2022-12-25 06:32 UTC, ramjay15 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> -1014
उचित स्थाने पृष्टसङ्ख्या स्थापितवान्।

2022-12-25 06:41 UTC, ramjay15 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +> '[पिण्डपितृयज्ञस्य करण'
इदानिम्   समीचीनम् कृतवान्।

2022-12-25 06:44 UTC, ramjay15 commented
नमस्ते।उक्त दोषा:समीचीकरणं कृतवान्।

On Sun, Dec 25, 2022 at 10:52 AM Vishvas Vasuki विश्वासः <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> <https://github.com/vishvAsa/vedAH_yajuH/pull/113#discussion_r1056902377>:
>
> >
> -జరుపుకుంకర
> +पिण्डपितृयज्ञं करिष्यन्नुपकल्पयते [^१]
> +सकृदाच्छिन्नं बहिर्दर्भागꣳश्च परिस्तरणीयान् व्रीहीꣳश्च शूर्पं च प्रक्षालिते चोलूखलमुसले स्थालीगꣳ सस्रुवाꣳ समेक्षणामेरकोपवर्हणे आञ्जनाभ्यञ्जने दशाꣳ स्फ्यमुदकुम्भं यज्ञायुधानीति।
> +[^१] यजमानः
>
> पादटिप्पनीविन्यासः सम्यङ् नास्ति। पुनः
> https://sanskrit.github.io/groups/dyuganga/projects/text/proofreading/editing/markdown/
> इति पश्यतु। रिक्तपङ्क्ती, :-चिह्नं च न दृश्यन्ते।
> ------------------------------
>
> In
> taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> <https://github.com/vishvAsa/vedAH_yajuH/pull/113#discussion_r1056902248>:
>
> >
> -1014
>
> रक्षितं न दृश्यत एव।
> ------------------------------
>
> In
> taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> <https://github.com/vishvAsa/vedAH_yajuH/pull/113#discussion_r1056902416>:
>
> >
> -1014
> +> '[पिण्डपितृयज्ञस्य करण'
>
> न रक्षितवान्। अन्यथा कुतः <details> … इत्यादिकं न दृश्यते?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/vishvAsa/vedAH_yajuH/pull/113#pullrequestreview-1229706818>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4IHOFKP5ON3OGUNVOEZI2LWO7KZRANCNFSM6AAAAAATDRQ5JE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-25 09:42 UTC, vvasuki commented
भोः, भवतः परिष्कारा नैव लब्धाः। सुब्रह्मण्यार्याय दर्शयित्वा, समीकृत्य प्रेषयतु।

2022-12-26 06:00 UTC, ramjay15 commented
> भोः, भवतः परिष्कारा नैव लब्धाः। सुब्रह्मण्यार्याय दर्शयित्वा, समीकृत्य प्रेषयतु।
नमस्ते।भवान् https://github.com/vishvAsa/vedAH_yajuH/pull/113 लिन्क् उद्घाटित्वा कृत शोधनं पश्यामि।यथा सुब्रह्मण्य भवान् स्वकार्यार्थं गतवान् सायंकालैव एतत् विषये चर्चां शक्नोमि। तावद् ऊर्धे वदित लिङ्क् उद्घाटित्वा  कृपया पुन: पश्यतु इति निवेदयामि

2022-12-26 16:29 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/52_piNDapitRyajnavidhiH.md
> +> '[पिण्डपितृयज्ञस्य करण'
न कृतम्। पुनः किं करणीयम् इत्य् अवगत्य, कृत्वा, सुब्रह्मण्यार्याय दर्शयित्वा वदतु।

2022-12-28 04:02 UTC, vvasuki commented
"Mahodaya namaste
From your above message, it seems I am not communicating properly. I am sorry if I have offended you inadvertently. I highly appreciate  your patience and feel I am not able to meet your requirement, even with Subramanian Mahodaya’s continuous help.
In view of the above with a heavy heart, I withdraw from this work.I feel disappointed I could not contribute to this noble cause.Krishnarpanam"

इति रमेशार्यः। तदन्व् अपूर्णम् अप्य् अशोधितम् अपि कार्यं सङ्गृह्यते।

2022-12-28 04:02 UTC, merged