रक्तवल्मीकाशनिविधिः तथा अशनिपात शान्ति विधिः शोधित्वा प्रेषितम्
vishvAsa/vedAH_yajuH pull request #115
Opened 2022-12-29 01:49 UTC by Malamanian

रक्तवल्मीकाशनिविधिः तथा अशनिपात शान्ति विधिः शोधित्वा प्रेषितम्

2022-12-29 01:51 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/18_ashanipAtashAntividhiH.md
> -693
पृष्ठसङ्ख्याः रक्षणीया इत्युक्तं खलु।  सर्वत्र यथापूर्वं यथोक्तं स्थापयतु।

2022-12-29 02:26 UTC, Malamanian commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/18_ashanipAtashAntividhiH.md
> -693
पृष्टसङ्ख्याः रक्षितवान्

2022-12-29 02:51 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/18_ashanipAtashAntividhiH.md
> -693
कुत्र? यथापूर्वम् एव दृश्यते।

2022-12-29 03:01 UTC, Malamanian commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/18_ashanipAtashAntividhiH.md
> -693
पुन; रक्षित्वा प्रेषितम्

2022-12-29 03:45 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/18_ashanipAtashAntividhiH.md
> -693
नैव काचित् पृष्ठसङ्ख्या दृश्यते। https://github.com/vishvAsa/vedAH_yajuH/pull/115/files इत्यत्र स्वयम् परीक्षितुं शक्नोति।

2022-12-29 03:46 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/17_raktavalmIkashAntividhiH.md
> +धर्माऽऽस्थाने तु वल्मीके जाते मरणमादिशेत् । [६९०]
पृष्ठसङ्ख्याः paragraph-खण्डयोर् मध्य एव रक्षणीयाः, न मध्ये (अनेन स्थानभेदस् स्यात् - तत्र चिन्ता नास्ति) । तथा च [[690]] इति स्यात्।  आङ्ग्ललिप्या पृष्ठसङ्ख्या लभ्यते चेत्, तयैव लिप्याऽस्तु। देवनागर्या लभ्यते चेत् तयैव लिप्या।

2022-12-29 03:47 UTC, vvasuki requested changes

2022-12-29 03:47 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/18_ashanipAtashAntividhiH.md
> -691
इयम् पृष्ठसङ्ख्या पुनर् आनेया।

2022-12-29 03:47 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/18_ashanipAtashAntividhiH.md
> -॥ ३४॥
इयम् पृष्ठसङ्ख्या पुनर् आनेया।

2022-12-29 03:47 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/18_ashanipAtashAntividhiH.md
> -692
इयम् पृष्ठसङ्ख्या पुनर् आनेया।

2022-12-29 11:08 UTC, Malamanian commented
Sir, Beg your pardon. Do I understand that the Page numbers should not be
in Devanagari but only in English/ Arabic numerals? The Text book (मूल
पुस्तकम्) does not contain page numbers. The section numbers are in
Devanagari. The page numbers are as per the pdf version. The encoded text
uses page numbers in separate lines in Arabic Number format without any
brackets. (Sample enclosed). Should the page numbers be enclosed within
double square brackets?  I had entered it in the middle of the sentence
wherever the page ended. I hope that is in order. However, sometimes, there
is a page break splitting or cutting a word. In such situations, would it
be appropriate to enter the page number in the middle of the word or after
the word ? I will make necessary corrections and give confirmation through
github after clearly understanding the requirements.
Yours sincerely R Subrahmanian

On Thu, 29 Dec 2022 at 09:18, Vishvas Vasuki विश्वासः <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In
> taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/18_ashanipAtashAntividhiH.md
> <https://github.com/vishvAsa/vedAH_yajuH/pull/115#discussion_r1058713523>:
>
> >
>
> -691
>
>
> इयम् पृष्ठसङ्ख्या पुनर् आनेया।
> ------------------------------
>
> In
> taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/18_ashanipAtashAntividhiH.md
> <https://github.com/vishvAsa/vedAH_yajuH/pull/115#discussion_r1058713581>:
>
> >
>
> -॥ ३४॥
>
>
> इयम् पृष्ठसङ्ख्या पुनर् आनेया।
> ------------------------------
>
> In
> taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/18_ashanipAtashAntividhiH.md
> <https://github.com/vishvAsa/vedAH_yajuH/pull/115#discussion_r1058713604>:
>
> >
>
> -692
>
>
> इयम् पृष्ठसङ्ख्या पुनर् आनेया।
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/vishvAsa/vedAH_yajuH/pull/115#pullrequestreview-1232160002>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4FR6DRP7PU45DDB5C5V6STWPUCXBANCNFSM6AAAAAATLWLGFQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-29 11:50 UTC, vvasuki commented
> Do I understand that the Page numbers should not be in Devanagari but only in English/ Arabic numerals? 

नैवम्। देवनागर्या लभ्यते चेद् देवनागर्या रक्षतु। आङ्ग्ललिप्या लभ्यते चेद् आङ्ग्ललिप्या। 

> The Text book (मूलपुस्तकम्) does not contain page numbers. The section numbers are in Devanagari. 

"section-numbers" इति यद् वदति, तान्य् अपि रक्षणीयानि। यथा - [[२२]]।   

> The page numbers are as per the pdf version. The encoded text uses page numbers in separate lines in Arabic Number format without any
brackets. (Sample enclosed). Should the page numbers be enclosed within
double square brackets?  

आम्, यथा [[123]].


> I had entered it in the middle of the sentence wherever the page ended. I hope that is in order. However, sometimes, there is a page break splitting or cutting a word. In such situations, would it be appropriate to enter the page number in the middle of the word or after the word ? 

सङ्ख्याः pagagraph मध्ये न स्युः, वाक्यमध्ये नैव, पदमध्ये नैव। स्थानम् ईषत् परिवर्त्य paragraph-समाप्तेः परम् अन्यत्र स्थापनीयाः सङ्ख्याः। यथा [अत्र](https://raw.githubusercontent.com/vishvAsa/AgamaH/content/AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md) (←उद्घाट्य पश्यतु)।

2022-12-29 16:27 UTC, Malamanian commented
नमामि।

भवान् मां क्षम्यताम्। मूलपुस्तके Section संख्या नास्ति, परन्तु एकैकं
काण्डस्य भिन्न भिन्न क्रम पृष्ट संख्या: वर्तन्ते, यथा 1. आह्निक काण्डस्य
पृष्ट संख्या 1 - 65 पर्यन्तम्, संस्कार काण्डस्य 1 - 210 पर्यन्तम्,
सङ्कीर्णकाण्डस्य  104 पर्यन्तम् तथा पितृमेधकाण्डस्य 103 पर्यन्तं वर्तन्ते।
तत्र मूलपुस्तके ऊर्ध्व भागं तथा अधो भागम् द्वौ अपि समान पृष्ट संख्या भवति।
(pdf मध्ये ऊर्ध्व तथा अधो भागस्य भिन्न भिन्न पृष्ट सङ्ख्या क्रमेण भवति)
 तेन एकैकं पृष्ट संख्या मूलपुस्तके पुनरावर्तनं भवति। केचित् कान्डे केवलम्
अधोभागे पृष्ट संख्या मुद्रितम्। अन्य केचित् काण्डे ऊर्ध्व भागे एकवारं,
अधोभागे द्वितीय वारं संख्या मुद्रितम्। तत्रापि पृष्टस्य आदौ एकवारं तथा
अवसाने द्वितीयं वारं मुद्रितम्।

उट्टङ्कन विषये मम अभिप्रायः - केवलं पृष्टस्य अन्तिमे (para-याः अपि अन्तिमे)
pdf पृष्ट सङ्ख्या उट्टङ्कनीयम्।  अथवा द्वावपि सङ्ख्यौ रक्षणीयं अवश्यकं किं
वा इति वदतु भवान्।
Format: पृष्ट सङ्ख्या - एकं रिक्त पङ्क्ति, तत्पश्चात् पङ्क्तौ द्वौ चतुस्र
कोष्टौ मध्ये [within double square brackets], तत्पश्चात् रिक्तपङ्क्त्येकम्
करणीयम्।
यदि पूर्वोक्त मुद्रित पृष्ट सङ्ख्याऽपि रक्षणीयं, तदा द्वौ सङ्ख्यौ कथं
भिन्नित करणीयम्।

भवदीय
सुब्रह्मण्यः

On Thu, 29 Dec 2022 at 17:20, Vishvas Vasuki विश्वासः <
***@***.***> wrote:

> Do I understand that the Page numbers should not be in Devanagari but only
> in English/ Arabic numerals?
>
> नैवम्। देवनागर्या लभ्यते चेद् देवनागर्या रक्षतु। आङ्ग्ललिप्या लभ्यते चेद्
> आङ्ग्ललिप्या।
>
> The Text book (मूलपुस्तकम्) does not contain page numbers. The section
> numbers are in Devanagari.
>
> "section-numbers" इति यद् वदति, तान्य् अपि रक्षणीयानि। यथा - [[२२]]।
>
> The page numbers are as per the pdf version. The encoded text uses page
> numbers in separate lines in Arabic Number format without any
> brackets. (Sample enclosed). Should the page numbers be enclosed within
> double square brackets?
>
> आम्, यथा [[123]].
>
> I had entered it in the middle of the sentence wherever the page ended. I
> hope that is in order. However, sometimes, there is a page break splitting
> or cutting a word. In such situations, would it be appropriate to enter the
> page number in the middle of the word or after the word ?
>
> सङ्ख्याः pagagraph मध्ये न स्युः, वाक्यमध्ये नैव, पदमध्ये नैव। स्थानम्
> ईषत् परिवर्त्य paragraph-समाप्तेः परम् अन्यत्र स्थापनीयाः सङ्ख्याः। यथा
> अत्र
> <https://raw.githubusercontent.com/vishvAsa/AgamaH/content/AryaH/hinduism/branches/vaiShNavaH/shrI-sampradAyaH/kriyA/gopAla-deshikaH/Ahnikam_AhnikArtha-prakAshikA/01_praveshaH.md>
> (←उद्घाट्य पश्यतु)।
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/vishvAsa/vedAH_yajuH/pull/115#issuecomment-1367265462>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4FR6DT44T6W7CT6NBXDUX3WPV3INANCNFSM6AAAAAATLWLGFQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-29 16:39 UTC, vvasuki commented
> उट्टङ्कन विषये मम अभिप्रायः - केवलं पृष्टस्य अन्तिमे (para-याः अपि अन्तिमे) pdf पृष्ट सङ्ख्या उट्टङ्कनीयम्। 

उट्टङ्कनश्रमो न स्यात्। परिष्क्रियमाणे पाठे पूर्वमेव सङ्ख्या परिष्करणीया दृश्येत - देवनागर्या काण्डपृष्ठसङ्ख्या, आङ्ग्ललिप्या pdf-पृष्ठ-सङ्ख्या। ते रक्ष्येताम्। 

> Format: पृष्ट सङ्ख्या - एकं रिक्त पङ्क्ति, तत्पश्चात् पङ्क्तौ द्वौ चतुस्र कोष्टौ मध्ये [within double square brackets], तत्पश्चात् रिक्तपङ्क्त्येकम् करणीयम्। 

साधु। किन्त्व् अनेन श्लोकच्छेदः, वाक्य-छेदो वा न स्यात्।

2022-12-29 16:47 UTC, Malamanian commented
धन्यवादः। एतदवगतम्। केवलं pdf पृष्ट संख्या रक्षणीयम् खलु?

On Thu, 29 Dec 2022 at 22:09, Vishvas Vasuki विश्वासः <
***@***.***> wrote:

> उट्टङ्कन विषये मम अभिप्रायः - केवलं पृष्टस्य अन्तिमे (para-याः अपि
> अन्तिमे) pdf पृष्ट सङ्ख्या उट्टङ्कनीयम्।
>
> उट्टङ्कनश्रमो न स्यात्। परिष्क्रियमाणे पाठे पूर्वमेव सङ्ख्या परिष्करणीया
> दृश्येत - देवनागर्या काण्डपृष्ठसङ्ख्या, आङ्ग्ललिप्या pdf-पृष्ठ-सङ्ख्या। ते
> रक्ष्येताम्।
>
> Format: पृष्ट सङ्ख्या - एकं रिक्त पङ्क्ति, तत्पश्चात् पङ्क्तौ द्वौ चतुस्र
> कोष्टौ मध्ये [within double square brackets], तत्पश्चात् रिक्तपङ्क्त्येकम्
> करणीयम्।
>
> साधु। किन्त्व् अनेन श्लोकच्छेदः, वाक्य-छेदो वा न स्यात्।
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/vishvAsa/vedAH_yajuH/pull/115#issuecomment-1367453704>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A4FR6DXB6SRZRUYR7UEUK3LWPW5E3ANCNFSM6AAAAAATLWLGFQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-12-29 17:07 UTC, vvasuki commented
> धन्यवादः। एतदवगतम्। केवलं pdf पृष्ट संख्या रक्षणीयम् खलु?

अस्तु नाम - तथैव करोतु। (काण्डसङ्ख्यायां रक्षितायाम् अपि कापि हानिर् नास्ति। )

2022-12-30 02:40 UTC, Malamanian commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/17_raktavalmIkashAntividhiH.md
> +धर्माऽऽस्थाने तु वल्मीके जाते मरणमादिशेत् । [६९०]
यथोक्तं तद्वत् पृष्टासङ्ख्यायाः स्थान परिवर्तनम् कृतवान्

2022-12-30 03:43 UTC, merged