Update 22_shayyAvidhiH.md
vishvAsa/vedAH_yajuH pull request #130
Opened 2023-03-01 04:54 UTC by vibhadiga

2023-03-01 10:16 UTC, vvasuki requested changes

2023-03-01 10:16 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/16_madhyAhnasandhyopAsanavidhiH.md
> + 'ॐ आसत्येन रज॑सा वर्तमानो निवेशयन्नमृतं मर्त्यं च । हिरण्ययेन सविता रथेना देवो याति भुवनाविपश्यन्' ॥
एतद् दीर्घोद्धरणवद् दर्श्यताम्।

2023-03-01 10:16 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/16_madhyAhnasandhyopAsanavidhiH.md
> +'ॐ य उदगान्महतोऽर्णवाद्विभ्राज॑मानः सरिरस्य मध्यात्समा वृषभो लोहिताक्षः सूर्यो विपश्चिन्मनसा पुनातु' इति पञ्चभिः ।। 'ॐ नमः प्राच्यै दिशे॰' इत्यादिदिगुपस्थानादिसर्वं प्रातःकालवत्कृत्वा, 'अनेन मध्याह्न
'ॐ य उदगान्महतोऽर्णवाद्विभ्राज॑मानः सरिरस्य मध्यात्समा वृषभो लोहिताक्षः सूर्यो विपश्चिन्मनसा पुनातु' - एतद् दीर्घोद्धरणवद् दर्श्यताम्।

2023-03-03 12:37 UTC, vvasuki requested changes

2023-03-03 12:37 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +> 'ॐ गं' इति जपम् ॥ ततः पूर्वोक्तप्रकारेण 'लं पृथिव्यात्मने नमः'
` इति जपम् ॥ ततः पूर्वोक्तप्रकारेण`

इत्य् उद्धरणाङ्गं कथम्?

2023-03-03 12:40 UTC, vvasuki requested changes

2023-03-03 12:40 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/09_sandhyopAsanavidhiH.md
> +> मूर्तित्रयस्य समुद्भवो यस्याः सा तथोक्तेति पञ्चमीबहुव्रीहिः । परो नाम परमात्मेत्यर्थः ॥
एतद् उद्धरणम् इति कथं निश्चितवती?

2023-03-03 12:40 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/09_sandhyopAsanavidhiH.md
> -
एतादृशानाम् इह पङ्क्तीनां निष्कासनं व्यर्थप्रायम्। एतादृशेषु स्थानेषु paragraph-भेदो न दोषाय।

2023-03-03 13:10 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +> 'ॐ गं' इति जपम् ॥ ततः पूर्वोक्तप्रकारेण 'लं पृथिव्यात्मने नमः'
Mayaa staapitam vaa mahodaya, purvam aseet tat tatra atah mayapi chintitam etat kathamiti, bhavata sthaapitam syaaditi chintitam mayaa

2023-03-03 13:12 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/16_madhyAhnasandhyopAsanavidhiH.md
> + 'ॐ आसत्येन रज॑सा वर्तमानो निवेशयन्नमृतं मर्त्यं च । हिरण्ययेन सविता रथेना देवो याति भुवनाविपश्यन्' ॥
दर्शितं महोदय

2023-03-03 13:13 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/16_madhyAhnasandhyopAsanavidhiH.md
> +'ॐ य उदगान्महतोऽर्णवाद्विभ्राज॑मानः सरिरस्य मध्यात्समा वृषभो लोहिताक्षः सूर्यो विपश्चिन्मनसा पुनातु' इति पञ्चभिः ।। 'ॐ नमः प्राच्यै दिशे॰' इत्यादिदिगुपस्थानादिसर्वं प्रातःकालवत्कृत्वा, 'अनेन मध्याह्न
आम्, दर्शितम्

2023-03-04 03:32 UTC, vvasuki requested changes

2023-03-04 03:32 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +> 'ॐ गं' इति जपम् ॥ ततः पूर्वोक्तप्रकारेण 'लं पृथिव्यात्मने नमः'
न हि मया स्थापितम्। असङ्गतं लक्षितं चेत् प्रष्टव्यो ऽहम्। समीकरोतु यथान्याय्यम्।

2023-03-06 17:06 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/09_sandhyopAsanavidhiH.md
> -
Astu

2023-03-06 17:11 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +> 'ॐ गं' इति जपम् ॥ ततः पूर्वोक्तप्रकारेण 'लं पृथिव्यात्मने नमः'
N8shkaasitam

2023-03-07 03:42 UTC, merged