29.03.2023
vishvAsa/vedAH_yajuH pull request #144
Opened 2023-03-29 15:10 UTC by surekhasamskrit

2023-03-29 15:18 UTC, vvasuki requested changes

2023-03-29 15:18 UTC, vvasuki commented on vAjasaneyam/mAdhyandinam/shatapatha-brAhmaNam/weber-srotaH/sasvaram/09/04/2.md
> +[^1]: आविपत्तिः (?) Sây.
? इति कुतोऽत्र?

2023-03-29 15:18 UTC, vvasuki commented on vAjasaneyam/mAdhyandinam/shatapatha-brAhmaNam/weber-srotaH/sasvaram/10/04/3.md
> +[^7]: पुरुषे Sây. (? पुरुष इति). - ibid. Sâyaṇa closes here the fourth adhyâya.
? इति कुतोऽत्र?

2023-03-29 15:18 UTC, vvasuki commented on vAjasaneyam/mAdhyandinam/shatapatha-brAhmaNam/weber-srotaH/sasvaram/09/03/1.md
> +[^3]: शफन Sây. (?).
? इति कुतोऽत्र?

2023-03-30 15:27 UTC, surekhasamskrit commented on vAjasaneyam/mAdhyandinam/shatapatha-brAhmaNam/weber-srotaH/sasvaram/09/04/2.md
> +[^1]: आविपत्तिः (?) Sây.
मूले अस्ति इत्यतः स्थापितम् ।

2023-03-30 15:27 UTC, surekhasamskrit commented on vAjasaneyam/mAdhyandinam/shatapatha-brAhmaNam/weber-srotaH/sasvaram/10/04/3.md
> +[^7]: पुरुषे Sây. (? पुरुष इति). - ibid. Sâyaṇa closes here the fourth adhyâya.
मूले अस्ति इत्यतः स्थापितम् ।

2023-03-30 15:27 UTC, surekhasamskrit commented on vAjasaneyam/mAdhyandinam/shatapatha-brAhmaNam/weber-srotaH/sasvaram/09/03/1.md
> +[^3]: शफन Sây. (?).
मूले अस्ति इत्यतः स्थापितम् ।

2023-03-30 15:30 UTC, merged