upto 569
vishvAsa/vedAH_yajuH pull request #183
Opened 2023-06-16 08:28 UTC by Dhunee

2023-06-16 13:56 UTC, vvasuki requested changes

2023-06-16 13:56 UTC, vvasuki commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/vangIpura-shrInivAsa-anukramaNikA.md
> +इति बध्वा
बद्ध्वा

2023-06-16 13:56 UTC, vvasuki commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/vangIpura-shrInivAsa-anukramaNikA.md
> +हिरण्यवर्णां हरिणीं सुवर्णरजतस्रजाम् ।
उद्धरणचिह्नं स्यात् खलु? कुतो ऽस्थापनकारको भ्रमः?

2023-06-16 13:56 UTC, vvasuki commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/vangIpura-shrInivAsa-anukramaNikA.md
> +नमो ब्रह्मणे नमो अस्त्वग्नये नमः पृथिव्यै नम ओषधीभ्यः ।
अत्रापि

2023-06-16 18:08 UTC, Dhunee commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/vangIpura-shrInivAsa-anukramaNikA.md
> +दर्भादिकं नैर्ऋत्यां निरस्याप उपस्पृश्य, तत्राग्निं प्रतिष्ठाप्य, याज्ञियैरिन्धनैः प्रज्वाल्य, परिसमूह्य अवोक्षणशेषं प्रागुदग्वोत्सृज्य अन्यञ्जलं पात्रे प्रागुदग्वा यथा परिस्तरणाद्बहिः स्यात्तथा निधा
नावगतम्

2023-06-16 18:09 UTC, Dhunee commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/vangIpura-shrInivAsa-anukramaNikA.md
> +- धात्रम् इदम् ।
समीक्रियते

2023-06-16 18:09 UTC, Dhunee commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/vangIpura-shrInivAsa-anukramaNikA.md
> +[[62]]ँ
अपवार्यते

2023-06-16 18:12 UTC, Dhunee commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/vangIpura-shrInivAsa-anukramaNikA.md
> +हिरण्यवर्णां हरिणीं सुवर्णरजतस्रजाम् ।
pdf इत्यत्र नासीदित्यतः न स्थापितम् । योजयामि

2023-06-16 18:12 UTC, Dhunee commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/vangIpura-shrInivAsa-anukramaNikA.md
> +नमो ब्रह्मणे नमो अस्त्वग्नये नमः पृथिव्यै नम ओषधीभ्यः ।
ओम्

2023-06-16 23:53 UTC, vvasuki commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/vangIpura-shrInivAsa-anukramaNikA.md
> +दर्भादिकं नैर्ऋत्यां निरस्याप उपस्पृश्य, तत्राग्निं प्रतिष्ठाप्य, याज्ञियैरिन्धनैः प्रज्वाल्य, परिसमूह्य अवोक्षणशेषं प्रागुदग्वोत्सृज्य अन्यञ्जलं पात्रे प्रागुदग्वा यथा परिस्तरणाद्बहिः स्यात्तथा निधा
![image](https://github.com/vishvAsa/vedAH_yajuH/assets/2664797/e61edcfc-5118-495d-a9ce-242fcaee3256)

2023-06-17 06:12 UTC, Dhunee commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/vangIpura-shrInivAsa-anukramaNikA.md
> +दर्भादिकं नैर्ऋत्यां निरस्याप उपस्पृश्य, तत्राग्निं प्रतिष्ठाप्य, याज्ञियैरिन्धनैः प्रज्वाल्य, परिसमूह्य अवोक्षणशेषं प्रागुदग्वोत्सृज्य अन्यञ्जलं पात्रे प्रागुदग्वा यथा परिस्तरणाद्बहिः स्यात्तथा निधा
परिहरामि

2023-06-17 06:13 UTC, Dhunee commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/vangIpura-shrInivAsa-anukramaNikA.md
> +दर्भादिकं नैर्ऋत्यां निरस्याप उपस्पृश्य, तत्राग्निं प्रतिष्ठाप्य, याज्ञियैरिन्धनैः प्रज्वाल्य, परिसमूह्य अवोक्षणशेषं प्रागुदग्वोत्सृज्य अन्यञ्जलं पात्रे प्रागुदग्वा यथा परिस्तरणाद्बहिः स्यात्तथा निधा
मार्जयामि ।

2023-06-18 09:11 UTC, merged