24.06.2023
vishvAsa/vedAH_yajuH pull request #194
Opened 2023-06-24 03:43 UTC by surekhasamskrit

2023-06-24 06:37 UTC, vvasuki commented on vAjasaneyam/mAdhyandinam/shatapatha-brAhmaNam/vaMshIdhara-pAThaH/sasvaram/02/04/4.md
> +पश्चाद्वै᳘ परीत्य व्वृषा यो᳘षाम᳘धिद्रवति त᳘स्याᳫँ᳭ रे᳘तः सिञ्चति स वै प्रा᳘गेवा᳘ग्रे जुहोत्य᳘ग्ने व्वीही᳘त्यनुव्व᳘षट्करोति त᳘त्स्विष्टकृद्भाजनᳫँ᳭ स वै प्रा᳘गेव᳘ जुहोति॥
व्वृषा इत्यत्र स्वरचिह्नं नास्ति वा? चित्रं दर्शयतु।

2023-06-24 06:37 UTC, vvasuki requested changes

2023-06-24 06:37 UTC, vvasuki commented on vAjasaneyam/mAdhyandinam/shatapatha-brAhmaNam/vaMshIdhara-pAThaH/sasvaram/02/04/4.md
> +त᳘ददस्त᳘त्पौर्णमास्यां᳘ क्रियते स यद्धात्रा᳘पि संन᳘येज्जामि᳘ कुर्यात्सम᳘दं कुर्यात्त᳘देनमद्भ्य ओ᳘षधिभ्यः सम्भृत्या᳘हुतिभ्यो᳘ ऽधिजनयति स᳘ ऽएष आ᳘हुतिभ्यो जातः पश्चा᳘द्ददृशे॥
जातः इत्यत्र स्वरचिह्नं नास्ति वा? चित्रं दर्शयतु।

2023-06-24 12:40 UTC, surekhasamskrit commented on vAjasaneyam/mAdhyandinam/shatapatha-brAhmaNam/vaMshIdhara-pAThaH/sasvaram/02/04/4.md
> +पश्चाद्वै᳘ परीत्य व्वृषा यो᳘षाम᳘धिद्रवति त᳘स्याᳫँ᳭ रे᳘तः सिञ्चति स वै प्रा᳘गेवा᳘ग्रे जुहोत्य᳘ग्ने व्वीही᳘त्यनुव्व᳘षट्करोति त᳘त्स्विष्टकृद्भाजनᳫँ᳭ स वै प्रा᳘गेव᳘ जुहोति॥
![image](https://github.com/vishvAsa/vedAH_yajuH/assets/69464487/47ea0592-db31-4ded-997f-4f6a498f1a64)
nasti mahodaya...

2023-06-24 12:42 UTC, surekhasamskrit commented on vAjasaneyam/mAdhyandinam/shatapatha-brAhmaNam/vaMshIdhara-pAThaH/sasvaram/02/04/4.md
> +त᳘ददस्त᳘त्पौर्णमास्यां᳘ क्रियते स यद्धात्रा᳘पि संन᳘येज्जामि᳘ कुर्यात्सम᳘दं कुर्यात्त᳘देनमद्भ्य ओ᳘षधिभ्यः सम्भृत्या᳘हुतिभ्यो᳘ ऽधिजनयति स᳘ ऽएष आ᳘हुतिभ्यो जातः पश्चा᳘द्ददृशे॥
![image](https://github.com/vishvAsa/vedAH_yajuH/assets/69464487/6c36e1cf-474d-450b-9101-44ddb16c766d)
nasti mahodaya...

2023-06-24 14:14 UTC, vvasuki commented on vAjasaneyam/mAdhyandinam/shatapatha-brAhmaNam/vaMshIdhara-pAThaH/sasvaram/02/04/4.md
> +पश्चाद्वै᳘ परीत्य व्वृषा यो᳘षाम᳘धिद्रवति त᳘स्याᳫँ᳭ रे᳘तः सिञ्चति स वै प्रा᳘गेवा᳘ग्रे जुहोत्य᳘ग्ने व्वीही᳘त्यनुव्व᳘षट्करोति त᳘त्स्विष्टकृद्भाजनᳫँ᳭ स वै प्रा᳘गेव᳘ जुहोति॥
परीत्य इत्यत्र स्वरचिह्नं दृश्यते - भवत्या न स्थापितं खलु?

अपि चेतः परं (अस्मात् परिवर्तनाद् आरभ्य) यत्र वर्तमानं स्वरचिह्नं निष्कास्यते, तत्र `[[स्वरभेदः??]]` इति योजयतु।

2023-06-30 01:25 UTC, vvasuki commented on vAjasaneyam/mAdhyandinam/shatapatha-brAhmaNam/vaMshIdhara-pAThaH/sasvaram/02/04/4.md
> +पश्चाद्वै᳘ परीत्य व्वृषा यो᳘षाम᳘धिद्रवति त᳘स्याᳫँ᳭ रे᳘तः सिञ्चति स वै प्रा᳘गेवा᳘ग्रे जुहोत्य᳘ग्ने व्वीही᳘त्यनुव्व᳘षट्करोति त᳘त्स्विष्टकृद्भाजनᳫँ᳭ स वै प्रा᳘गेव᳘ जुहोति॥
अथवा वरम् [[???]] इति सङ्क्षेपार्थं स्थापयतु। तथा च स्वरनिष्कासन-स्थानानि चातुर्येणाल्पश्रमेणानेन जालक्षेत्रेण ज्ञायन्ताम् - https://github.com/vishvAsa/vedAH_yajuH/pull/194/files ।

2023-07-05 10:16 UTC, surekhasamskrit commented on vAjasaneyam/mAdhyandinam/shatapatha-brAhmaNam/vaMshIdhara-pAThaH/sasvaram/02/04/4.md
> +पश्चाद्वै᳘ परीत्य व्वृषा यो᳘षाम᳘धिद्रवति त᳘स्याᳫँ᳭ रे᳘तः सिञ्चति स वै प्रा᳘गेवा᳘ग्रे जुहोत्य᳘ग्ने व्वीही᳘त्यनुव्व᳘षट्करोति त᳘त्स्विष्टकृद्भाजनᳫँ᳭ स वै प्रा᳘गेव᳘ जुहोति॥
Astu mahodaya..

2023-07-06 07:28 UTC, merged