upto 105
vishvAsa/vedAH_yajuH pull request #208
Opened 2023-07-10 12:54 UTC by Dhunee

2023-07-11 01:29 UTC, vvasuki requested changes

2023-07-11 01:29 UTC, vvasuki commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/uttamUru-vIrarAghavArya-prayoga-mAlA/10_brahmakUrchapanchagavyavidhiH.md
> +दध्नि – ब्रह्म॑जज्ञा॒नं प्र॑थ॒मं पु॒रस्ता᳚त् । विसी॑म॒तस्सु॒रुचो॑ वे॒न आ॑वः ।
उद्धरणचिह्नम्

2023-07-11 01:29 UTC, vvasuki commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/uttamUru-vIrarAghavArya-prayoga-mAlA/10_brahmakUrchapanchagavyavidhiH.md
> +    (इति मन्त्रेण) वसुं वा आवाहयामि ।)
आदाव् अनपेक्षितानि रिक्तस्थानानि।

2023-07-11 01:29 UTC, vvasuki commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/uttamUru-vIrarAghavArya-prayoga-mAlA/10_brahmakUrchapanchagavyavidhiH.md
> +    > वस॑वो॒ रु॒द्रा आ॑दि॒त्या उ॑परि॒स्प॒शं॑ मो॒ग्रं चेत्ता॑रमधि रा॒जम॑क्रन्न् ।
उद्धरणात् पूर्वं रिक्ता स्यात् पङ्क्तिः।

2023-07-12 10:51 UTC, Dhunee commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/uttamUru-vIrarAghavArya-prayoga-mAlA/10_brahmakUrchapanchagavyavidhiH.md
> +    (इति मन्त्रेण) वसुं वा आवाहयामि ।)
परिह्रियते

2023-07-12 10:51 UTC, Dhunee commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/uttamUru-vIrarAghavArya-prayoga-mAlA/10_brahmakUrchapanchagavyavidhiH.md
> +दध्नि – ब्रह्म॑जज्ञा॒नं प्र॑थ॒मं पु॒रस्ता᳚त् । विसी॑म॒तस्सु॒रुचो॑ वे॒न आ॑वः ।
संयोज्यते

2023-07-12 10:51 UTC, Dhunee commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/uttamUru-vIrarAghavArya-prayoga-mAlA/10_brahmakUrchapanchagavyavidhiH.md
> +    > वस॑वो॒ रु॒द्रा आ॑दि॒त्या उ॑परि॒स्प॒शं॑ मो॒ग्रं चेत्ता॑रमधि रा॒जम॑क्रन्न् ।
अध्याह्रियते

2023-07-12 11:42 UTC, vvasuki commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/uttamUru-vIrarAghavArya-prayoga-mAlA/10_brahmakUrchapanchagavyavidhiH.md
> +    (इति मन्त्रेण) वसुं वा आवाहयामि ।)
रिक्तस्थानानि = space-bar-तः लभ्यमानम्
रिक्तपङ्क्तिः = enter-तः लभ्यमानम्

2023-07-12 11:44 UTC, vvasuki commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/uttamUru-vIrarAghavArya-prayoga-mAlA/10_brahmakUrchapanchagavyavidhiH.md
> +दध्नि – ब्रह्म॑जज्ञा॒नं प्र॑थ॒मं पु॒रस्ता᳚त् । विसी॑म॒तस्सु॒रुचो॑ वे॒न आ॑वः ।
परिष्करणात् पूर्वं नात्रोत्तरं लेख्यम्। करणाद् अनन्तरं तु लेख्यम्, येन सुकृतं न वेति परीक्षितुं शक्नुयाम्।

2023-07-13 01:20 UTC, merged