१०६
vishvAsa/vedAH_yajuH pull request #210
Opened 2023-07-13 12:54 UTC by Manjuhegde282

2023-07-13 13:48 UTC, vvasuki requested changes
प्रायेण सम्यक् कृतम्। कश्चन दोषः सूचितः।

2023-07-13 13:48 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/02_vinAyakakalpaH.md
एवम् अध्याहृतः पाठो विन्यस्तश् चेत्, अग्रिमपाठात् पूर्वं ("इति" इत्यस्मात् पूर्वम् अत्र) रिक्ता पङ्क्तिर् नेष्यते।

2023-07-27 02:36 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/02_vinAyakakalpaH.md
अस्योत्तरं नैव लब्धम्

2023-08-07 03:07 UTC, vvasuki commented
कार्यगतिर् अतिमन्दा। नैतद् अनुवर्तयितुम् उचितम्।  स्वस्ति।

2023-08-07 03:07 UTC, merged

2023-08-13 07:01 UTC, Manjuhegde282 commented
aam sir... Mandam bhavati pratyam kartum na shaknomi.. admission jayamanam
asti punaha kakshya api chalati... Kim karthavyam ityeva na jnayate...

On Mon, 7 Aug, 2023, 8:37 am Vishvas Vasuki विश्वासः, <
***@***.***> wrote:

> कार्यगतिर् अतिमन्दा। नैतद् अनुवर्तयितुम् उचितम्। स्वस्ति।
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/vishvAsa/vedAH_yajuH/pull/210#issuecomment-1667118802>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BBAXADA3PQ67AXH4AGQJUDLXUBLX5ANCNFSM6AAAAAA2I44SWY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-13 07:19 UTC, Manjuhegde282 commented
Punashcha network samasyapi vartate...

On Sun, 13 Aug, 2023, 12:31 pm Manjunath Hegde, <
***@***.***> wrote:

> aam sir... Mandam bhavati pratyam kartum na shaknomi.. admission jayamanam
> asti punaha kakshya api chalati... Kim karthavyam ityeva na jnayate...
>
> On Mon, 7 Aug, 2023, 8:37 am Vishvas Vasuki विश्वासः, <
> ***@***.***> wrote:
>
>> कार्यगतिर् अतिमन्दा। नैतद् अनुवर्तयितुम् उचितम्। स्वस्ति।
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/vishvAsa/vedAH_yajuH/pull/210#issuecomment-1667118802>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/BBAXADA3PQ67AXH4AGQJUDLXUBLX5ANCNFSM6AAAAAA2I44SWY>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>