विभागचिह्नितम्
vishvAsa/vedAH_yajuH pull request #304
Opened 2023-10-30 16:24 UTC by Dhunee

2023-10-31 02:40 UTC, vvasuki requested changes

2023-10-31 02:40 UTC, vvasuki commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/shrInivAsa-deshikaH/02_apara-prayogaH.md
> +## 1. LILITGNO¥
किम् इदं विचित्रम्??

2023-10-31 02:40 UTC, vvasuki commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/shrInivAsa-deshikaH/02_apara-prayogaH.md
> +## आपस्तम्बीयोऽपरप्रयोगः
नेयं  पाठविभाग-सूचना काचित्। इतो ## इति निष्कासयतु।

2023-10-31 02:40 UTC, vvasuki commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/shrInivAsa-deshikaH/02_apara-prayogaH.md
> +## Conclusion
अत्र यावत् सर्वाः आङ्ग्लविभागशीर्षिका उपविभागा इति कुर्यात् - ### इति चिह्नेन

2023-10-31 02:40 UTC, vvasuki commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/shrInivAsa-deshikaH/02_apara-prayogaH.md
अग्रे ## विषयसूचितेति विभागं निवेशयेत्।

2023-10-31 02:40 UTC, vvasuki commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/shrInivAsa-deshikaH/02_apara-prayogaH.md
अत्र `## श्रीनिवास-प्रस्तावः ` इति निवेशयेत्।

2023-10-31 14:56 UTC, Dhunee commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/shrInivAsa-deshikaH/02_apara-prayogaH.md
om

2023-10-31 14:56 UTC, Dhunee commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/shrInivAsa-deshikaH/02_apara-prayogaH.md
> +## Conclusion
om

2023-10-31 15:02 UTC, Dhunee commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/shrInivAsa-deshikaH/02_apara-prayogaH.md
> +## 1. LILITGNO¥
समीक्रियते

2023-10-31 15:02 UTC, Dhunee commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/shrInivAsa-deshikaH/02_apara-prayogaH.md
> +## आपस्तम्बीयोऽपरप्रयोगः
ओम्

2023-10-31 15:02 UTC, Dhunee commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/shrInivAsa-deshikaH/02_apara-prayogaH.md
> +## Conclusion
ओम्

2023-10-31 15:03 UTC, Dhunee commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/shrInivAsa-deshikaH/02_apara-prayogaH.md
## विषयसूचितेति विभागं निवेशयेत्। 

इत्थमेव पङ्क्तिः निवेश्या वा?

2023-10-31 16:24 UTC, vvasuki commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/shrInivAsa-deshikaH/02_apara-prayogaH.md
क्षम्यताम्  - टङ्कनदोषम् मार्जयित्वा 

`## विषयसूचिका`

इति निवेशयतु।

2023-11-01 16:31 UTC, Dhunee commented on taittirIyam/sUtram/ApastambaH/gRhyam/paddhatiH/shrIvaiShNavaH/shrInivAsa-deshikaH/02_apara-prayogaH.md
ओम्

2023-11-01 23:37 UTC, merged