Content
vishvAsa/vedAH_yajuH pull request #346
Opened 2024-01-23 05:02 UTC by Vidyadharbhat

2024-01-24 14:53 UTC, vvasuki requested changes

2024-01-24 14:53 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति (स्त्रीणामयम्मन्त्रो वर्ज्यः) नदीसमुद्रेषु वाऽभ्यवहरन्त्यपि वा पुरुषसम्मितं गर्तं कृत्वा तस्मिन्कुम्भमवधाय पुनरभ्यर्च्य मृत्तिकाभिः प्रच्छादयेत् । एतद्यावद्वसति तावत्स्वर्गे महीयते ॥ अथ जधनेन कुम
उद्वयन्तमसस्परि॰ रुत्तमम्' इत्यत्रोद्धरणं कुतो नाभिज्ञातम्? 
अन्याप्य् अयं दोषो ऽस्यां सञ्चिकायां दृश्यते।  
इतिकारे जागरूको भवतु, समीकृत्य, पुनः सर्वत्र find तन्त्रेणान्विष्य परीक्ष्य वदतु

2024-01-25 04:50 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति (स्त्रीणामयम्मन्त्रो वर्ज्यः) नदीसमुद्रेषु वाऽभ्यवहरन्त्यपि वा पुरुषसम्मितं गर्तं कृत्वा तस्मिन्कुम्भमवधाय पुनरभ्यर्च्य मृत्तिकाभिः प्रच्छादयेत् । एतद्यावद्वसति तावत्स्वर्गे महीयते ॥ अथ जधनेन कुम
किमिति न ज्ञातम्

2024-01-25 06:08 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति (स्त्रीणामयम्मन्त्रो वर्ज्यः) नदीसमुद्रेषु वाऽभ्यवहरन्त्यपि वा पुरुषसम्मितं गर्तं कृत्वा तस्मिन्कुम्भमवधाय पुनरभ्यर्च्य मृत्तिकाभिः प्रच्छादयेत् । एतद्यावद्वसति तावत्स्वर्गे महीयते ॥ अथ जधनेन कुम
edit-find इति कृत्वा, अथवा Ctrl+F इति कृत्वा, "इत" इति वर्णद्वयम् अन्विष्य, प्रतिस्थानम् उद्धरणं सम्यग् विन्यस्तं वेति विज्ञाय वदतु। 
अपि च "किम् इति न ज्ञातम्" इत्य् अस्पष्टम् भवति। पूर्णतरवाक्येन वदतु, यथा 

> यद् "/..." इत्य् उक्तम्, तत् किम् इति न ज्ञातम्।

2024-01-25 06:28 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति (स्त्रीणामयम्मन्त्रो वर्ज्यः) नदीसमुद्रेषु वाऽभ्यवहरन्त्यपि वा पुरुषसम्मितं गर्तं कृत्वा तस्मिन्कुम्भमवधाय पुनरभ्यर्च्य मृत्तिकाभिः प्रच्छादयेत् । एतद्यावद्वसति तावत्स्वर्गे महीयते ॥ अथ जधनेन कुम
उद्वयन्तमसस्परि॰ रुत्तमम्' इत्यत्रोद्धरणं कुतो नाभिज्ञातम्? 
पूर्वं‌ प्रारम्भोद्धरणचिह्नं‌ सम्यक् न स्थापितमासीत् , अधुना स्थापितम्

2024-01-25 06:30 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति (स्त्रीणामयम्मन्त्रो वर्ज्यः) नदीसमुद्रेषु वाऽभ्यवहरन्त्यपि वा पुरुषसम्मितं गर्तं कृत्वा तस्मिन्कुम्भमवधाय पुनरभ्यर्च्य मृत्तिकाभिः प्रच्छादयेत् । एतद्यावद्वसति तावत्स्वर्गे महीयते ॥ अथ जधनेन कुम
"इत" इति वर्णद्वयम्प्रति उद्धरणचिह्नं‌ दातव्यं‌ वा?‌

2024-01-25 06:37 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति (स्त्रीणामयम्मन्त्रो वर्ज्यः) नदीसमुद्रेषु वाऽभ्यवहरन्त्यपि वा पुरुषसम्मितं गर्तं कृत्वा तस्मिन्कुम्भमवधाय पुनरभ्यर्च्य मृत्तिकाभिः प्रच्छादयेत् । एतद्यावद्वसति तावत्स्वर्गे महीयते ॥ अथ जधनेन कुम
यत्र यत्र तादृशस्थानय् उद्धरणम् अभिजानाति, तत्र तत्र +उद्धरणवद्-विन्यासो यथाशिक्षितं विधेयः।

2024-01-25 08:31 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति (स्त्रीणामयम्मन्त्रो वर्ज्यः) नदीसमुद्रेषु वाऽभ्यवहरन्त्यपि वा पुरुषसम्मितं गर्तं कृत्वा तस्मिन्कुम्भमवधाय पुनरभ्यर्च्य मृत्तिकाभिः प्रच्छादयेत् । एतद्यावद्वसति तावत्स्वर्गे महीयते ॥ अथ जधनेन कुम
क्षम्यताम्, 
विस्मृतवानस्मि उदारणार्थम् एकं‌ वाक्यं‌ प्रेषयितुं‌ शक्यते वा ?

2024-01-25 08:47 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति (स्त्रीणामयम्मन्त्रो वर्ज्यः) नदीसमुद्रेषु वाऽभ्यवहरन्त्यपि वा पुरुषसम्मितं गर्तं कृत्वा तस्मिन्कुम्भमवधाय पुनरभ्यर्च्य मृत्तिकाभिः प्रच्छादयेत् । एतद्यावद्वसति तावत्स्वर्गे महीयते ॥ अथ जधनेन कुम
कस्योदाहरणम् इच्छति?  उद्धरणानां चेट् टॆलिग्रामि jan 14 इति देने प्रेषितं सन्देशम् ईक्षताम्।

2024-01-25 09:10 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति (स्त्रीणामयम्मन्त्रो वर्ज्यः) नदीसमुद्रेषु वाऽभ्यवहरन्त्यपि वा पुरुषसम्मितं गर्तं कृत्वा तस्मिन्कुम्भमवधाय पुनरभ्यर्च्य मृत्तिकाभिः प्रच्छादयेत् । एतद्यावद्वसति तावत्स्वर्गे महीयते ॥ अथ जधनेन कुम
हृस्वोद्धरणानि साधु वा?‌ उत तत्रैव दोषः अस्ति वा?‌

2024-01-25 10:01 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति (स्त्रीणामयम्मन्त्रो वर्ज्यः) नदीसमुद्रेषु वाऽभ्यवहरन्त्यपि वा पुरुषसम्मितं गर्तं कृत्वा तस्मिन्कुम्भमवधाय पुनरभ्यर्च्य मृत्तिकाभिः प्रच्छादयेत् । एतद्यावद्वसति तावत्स्वर्गे महीयते ॥ अथ जधनेन कुम
चित्रे वीक्षताम् - दर्शिते स्थाने दोषः -०

![image](https://github.com/vishvAsa/vedAH_yajuH/assets/2664797/c5dcff67-8ca2-44f3-9048-2a57012a79c2)

2024-01-25 15:03 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति (स्त्रीणामयम्मन्त्रो वर्ज्यः) नदीसमुद्रेषु वाऽभ्यवहरन्त्यपि वा पुरुषसम्मितं गर्तं कृत्वा तस्मिन्कुम्भमवधाय पुनरभ्यर्च्य मृत्तिकाभिः प्रच्छादयेत् । एतद्यावद्वसति तावत्स्वर्गे महीयते ॥ अथ जधनेन कुम
आम्, तेन यथापेक्षितम् उद्धरणविन्यासो नास्तीति।

2024-01-27 05:15 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति (स्त्रीणामयम्मन्त्रो वर्ज्यः) नदीसमुद्रेषु वाऽभ्यवहरन्त्यपि वा पुरुषसम्मितं गर्तं कृत्वा तस्मिन्कुम्भमवधाय पुनरभ्यर्च्य मृत्तिकाभिः प्रच्छादयेत् । एतद्यावद्वसति तावत्स्वर्गे महीयते ॥ अथ जधनेन कुम
हो, इदानीमवगतम् 

कृतमस्ति,

2024-01-27 06:07 UTC, vvasuki requested changes

2024-01-27 06:07 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति सङ्कल्प्य दहनाऽग्निं दक्षिणतो निरूह्य ( दहनाऽग्न्यनुगते लौकिकाऽग्निमुपसमाधाय पूर्वोक्तप्रायश्चित्तं कृत्वा) सञ्चयनहोमः कर्म, पैतृकं तन्त्रम्, कव्यादो नामाऽग्निः, अग्निर्जातवेदा इत्यादयो देवताः, आ
ऊर्ध्वम् उद्धरणं साधु-विन्यस्यतु, पाठं च परीक्षताम्।

2024-01-27 06:07 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +शान्तिहोमप्रयोगः ॥ कर्ता कृतसर्वाङ्गवपनो नद्यादौ स्नात्वा ग्रामश्मशानयोर्मध्ये शुचौ देशे प्राङ्मुख उपविश्य पवित्रपाणिराचम्य प्राणानायम्य देशकालौ सङ्कीर्त्य ( यज्ञोपवीत्येव ) ज्ञातीनां मम च सर्वेषामघन
अत्र पुनः परीक्षताम्।

2024-01-27 06:09 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति (स्त्रीणामयम्मन्त्रो वर्ज्यः) नदीसमुद्रेषु वाऽभ्यवहरन्त्यपि वा पुरुषसम्मितं गर्तं कृत्वा तस्मिन्कुम्भमवधाय पुनरभ्यर्च्य मृत्तिकाभिः प्रच्छादयेत् । एतद्यावद्वसति तावत्स्वर्गे महीयते ॥ अथ जधनेन कुम
न कृतम् इति मे भाति। पुनरुक्तवर्णय् अन्विष्य परीक्षताम्। 
सद्यः स्पृष्टाः सञ्चिकाः पङ्क्तीश् च परिष्कृत्य सूचयित्वैवानुज्ञातो ऽङ्ग्रे ऽनुवर्तताम्।

2024-01-27 11:31 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति (स्त्रीणामयम्मन्त्रो वर्ज्यः) नदीसमुद्रेषु वाऽभ्यवहरन्त्यपि वा पुरुषसम्मितं गर्तं कृत्वा तस्मिन्कुम्भमवधाय पुनरभ्यर्च्य मृत्तिकाभिः प्रच्छादयेत् । एतद्यावद्वसति तावत्स्वर्गे महीयते ॥ अथ जधनेन कुम
11_asthisanchayanavidhiH.md

इदानीमेकवारं‌ पश्यतु

2024-01-27 11:36 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति सङ्कल्प्य दहनाऽग्निं दक्षिणतो निरूह्य ( दहनाऽग्न्यनुगते लौकिकाऽग्निमुपसमाधाय पूर्वोक्तप्रायश्चित्तं कृत्वा) सञ्चयनहोमः कर्म, पैतृकं तन्त्रम्, कव्यादो नामाऽग्निः, अग्निर्जातवेदा इत्यादयो देवताः, आ
> अमुकगोत्रस्य॰ प्रेतस्य प्रेतत्वनिवृत्त्याऽक्षय्यपुण्यलोकप्राप्त्यर्थमस्थिसञ्चयनं करिष्ये

अत्रत्य उद्धरणं‌ सम्यक् न कृतवान् वा?‌

2024-01-27 11:51 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +शान्तिहोमप्रयोगः ॥ कर्ता कृतसर्वाङ्गवपनो नद्यादौ स्नात्वा ग्रामश्मशानयोर्मध्ये शुचौ देशे प्राङ्मुख उपविश्य पवित्रपाणिराचम्य प्राणानायम्य देशकालौ सङ्कीर्त्य ( यज्ञोपवीत्येव ) ज्ञातीनां मम च सर्वेषामघन
कर्तृन् इत्यस्मिन् स्थाने **कर्तॄन्** इति भवेत्

2024-01-27 12:02 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +शान्तिहोमप्रयोगः ॥ कर्ता कृतसर्वाङ्गवपनो नद्यादौ स्नात्वा ग्रामश्मशानयोर्मध्ये शुचौ देशे प्राङ्मुख उपविश्य पवित्रपाणिराचम्य प्राणानायम्य देशकालौ सङ्कीर्त्य ( यज्ञोपवीत्येव ) ज्ञातीनां मम च सर्वेषामघन
सञ्चयनहोमः कर्म, पैतृकं तन्त्रम्, कव्यादो नामाऽग्निः, अग्निर्जातवेदा इत्यादयो देवताः, आज्यं हविः, सद्यो यक्ष्ये, इत्यादि सङ्क ल्प्या
 
 इति सावधानम् अवलोक्य चिन्तयतु।

2024-01-27 12:03 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति सङ्कल्प्य दहनाऽग्निं दक्षिणतो निरूह्य ( दहनाऽग्न्यनुगते लौकिकाऽग्निमुपसमाधाय पूर्वोक्तप्रायश्चित्तं कृत्वा) सञ्चयनहोमः कर्म, पैतृकं तन्त्रम्, कव्यादो नामाऽग्निः, अग्निर्जातवेदा इत्यादयो देवताः, आ
सञ्चयनहोमः कर्म, पैतृकं तन्त्रम्, कव्यादो नामाऽग्निः, अग्निर्जातवेदा इत्यादयो देवताः, आज्यं हविः, सद्यो यक्ष्ये, इत्यादि सङ्क ल्प्या

2024-01-27 12:03 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +शान्तिहोमप्रयोगः ॥ कर्ता कृतसर्वाङ्गवपनो नद्यादौ स्नात्वा ग्रामश्मशानयोर्मध्ये शुचौ देशे प्राङ्मुख उपविश्य पवित्रपाणिराचम्य प्राणानायम्य देशकालौ सङ्कीर्त्य ( यज्ञोपवीत्येव ) ज्ञातीनां मम च सर्वेषामघन
"इति सङ्कल्प्य" इति वर्तते चेत् पूर्वं वर्तमानम् उद्धरणम् एवेति ज्ञायताम्।

2024-01-27 13:48 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +शान्तिहोमप्रयोगः ॥ कर्ता कृतसर्वाङ्गवपनो नद्यादौ स्नात्वा ग्रामश्मशानयोर्मध्ये शुचौ देशे प्राङ्मुख उपविश्य पवित्रपाणिराचम्य प्राणानायम्य देशकालौ सङ्कीर्त्य ( यज्ञोपवीत्येव ) ज्ञातीनां मम च सर्वेषामघन
तर्हि तादृश स्थलेऽपि उद्धारणचिह्नं‌ दातव्यं‌ वा?‌

2024-01-27 13:51 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति सङ्कल्प्य दहनाऽग्निं दक्षिणतो निरूह्य ( दहनाऽग्न्यनुगते लौकिकाऽग्निमुपसमाधाय पूर्वोक्तप्रायश्चित्तं कृत्वा) सञ्चयनहोमः कर्म, पैतृकं तन्त्रम्, कव्यादो नामाऽग्निः, अग्निर्जातवेदा इत्यादयो देवताः, आ
एतादृश स्थलमपि उद्धरणचिह्ने दर्शनीयानि किम्?‌

2024-01-27 14:08 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +शान्तिहोमप्रयोगः ॥ कर्ता कृतसर्वाङ्गवपनो नद्यादौ स्नात्वा ग्रामश्मशानयोर्मध्ये शुचौ देशे प्राङ्मुख उपविश्य पवित्रपाणिराचम्य प्राणानायम्य देशकालौ सङ्कीर्त्य ( यज्ञोपवीत्येव ) ज्ञातीनां मम च सर्वेषामघन
अवश्यम्। ननु [https://sanskrit.github.io/groups/dyuganga/projects/text/proofreading/editing/markdown/Quotes/ इत्यत्रोद्धरण-लक्षणं स्पष्टम् उक्तम्।

2024-01-27 14:08 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति सङ्कल्प्य दहनाऽग्निं दक्षिणतो निरूह्य ( दहनाऽग्न्यनुगते लौकिकाऽग्निमुपसमाधाय पूर्वोक्तप्रायश्चित्तं कृत्वा) सञ्चयनहोमः कर्म, पैतृकं तन्त्रम्, कव्यादो नामाऽग्निः, अग्निर्जातवेदा इत्यादयो देवताः, आ
अवश्यम्। ननु [https://sanskrit.github.io/groups/dyuganga/projects/text/proofreading/editing/markdown/Quotes/ इत्यत्रोद्धरण-लक्षणं स्पष्टम् उक्तम्।  पुनर् अवलोक्य प्रश्ने सति पृच्छतु।

2024-01-28 14:17 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति सङ्कल्प्य दहनाऽग्निं दक्षिणतो निरूह्य ( दहनाऽग्न्यनुगते लौकिकाऽग्निमुपसमाधाय पूर्वोक्तप्रायश्चित्तं कृत्वा) सञ्चयनहोमः कर्म, पैतृकं तन्त्रम्, कव्यादो नामाऽग्निः, अग्निर्जातवेदा इत्यादयो देवताः, आ
इदानीमेकवारं‌ परीक्ष्यताम् ।

2024-01-29 01:02 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति सङ्कल्प्य दहनाऽग्निं दक्षिणतो निरूह्य ( दहनाऽग्न्यनुगते लौकिकाऽग्निमुपसमाधाय पूर्वोक्तप्रायश्चित्तं कृत्वा) सञ्चयनहोमः कर्म, पैतृकं तन्त्रम्, कव्यादो नामाऽग्निः, अग्निर्जातवेदा इत्यादयो देवताः, आ
```
> सञ्चयनहोमः कर्म, पैतृकं तन्त्रम्, कव्यादो नामाऽग्निः, अग्निर्जातवेदा इत्यादयो देवताः, आज्यं हविः, सद्यो यक्ष्ये

इत्यादि सङ्कल्प्याऽन्वाधायाऽऽज्यस्थालीं
```

इति करोतु, यतो यजमानः सर्वम् एतद् वदति।

2024-01-29 13:09 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/11_asthisanchayanavidhiH.md
> +इति सङ्कल्प्य दहनाऽग्निं दक्षिणतो निरूह्य ( दहनाऽग्न्यनुगते लौकिकाऽग्निमुपसमाधाय पूर्वोक्तप्रायश्चित्तं कृत्वा) सञ्चयनहोमः कर्म, पैतृकं तन्त्रम्, कव्यादो नामाऽग्निः, अग्निर्जातवेदा इत्यादयो देवताः, आ
कृतवानस्मि।

2024-01-29 13:36 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +शान्तिहोमप्रयोगः ॥ कर्ता कृतसर्वाङ्गवपनो नद्यादौ स्नात्वा ग्रामश्मशानयोर्मध्ये शुचौ देशे प्राङ्मुख उपविश्य पवित्रपाणिराचम्य प्राणानायम्य देशकालौ सङ्कीर्त्य ( यज्ञोपवीत्येव ) ज्ञातीनां मम च सर्वेषामघन
अत्रोत्तरं न लब्धम्

2024-01-29 13:45 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +शान्तिहोमप्रयोगः ॥ कर्ता कृतसर्वाङ्गवपनो नद्यादौ स्नात्वा ग्रामश्मशानयोर्मध्ये शुचौ देशे प्राङ्मुख उपविश्य पवित्रपाणिराचम्य प्राणानायम्य देशकालौ सङ्कीर्त्य ( यज्ञोपवीत्येव ) ज्ञातीनां मम च सर्वेषामघन
हो, क्षम्यताम् विस्मृतवान् 
इदमेव दृष्ट्वा अहं‌  
सञ्चयनहोमः कर्म, पैतृकं तन्त्रम् ...... इत्यत्र उद्धरणचिह्नं‌ योजितवान् ।

2024-01-29 14:52 UTC, vvasuki requested changes

2024-01-29 14:52 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +इति ॥ ( बो. पि. सू. २. ४. १८-१९ ) यथो एतत् गृहानेष्यन्नुपकल्पयत इति स्वान् स्वान् गृहस्थधर्मान्प्रतिपत्स्यान्नित्येवेदमुक्तं भवति । नाऽशुचिः काम्यं तप आतिष्ठेन्न यजेन्न स्वाध्यायमधीयीतान्यत्राग्निहोत
अस्याम् पङ्क्तौ मम संशयः। सदयम् अस्य चित्रम् इह दर्शयतु।

2024-01-29 14:52 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +दशमदिनप्रयोगः॥ कर्ता स्नात्वा नित्यपिण्डदानादिकं प्रातःसायं करिष्यमाणं समानतन्त्रेण निर्वर्त्य पिण्डौ सुरक्षितं स्थापयेत् । प्रभूतबल्यर्थमाज्यं दधि मधु क्षीरं कार्पासं वस्त्रमुपवीतं पिष्टमयछत्रपादुके
उपतिष्ठतः ?? पुनः परीक्षताम्। संशयास्पदम्। अपि चोद्धरणं नेदं कुतः?

2024-01-29 14:52 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +शान्तिहोमप्रयोगः ॥ कर्ता कृतसर्वाङ्गवपनो नद्यादौ स्नात्वा ग्रामश्मशानयोर्मध्ये शुचौ देशे प्राङ्मुख उपविश्य पवित्रपाणिराचम्य प्राणानायम्य देशकालौ सङ्कीर्त्य ( यज्ञोपवीत्येव ) ज्ञातीनां मम च सर्वेषामघन
तद् अन्यत्र परिष्कृतम् अस्तु। अत्र तादृशम् अन्यद् एव परिष्कार्यम्। एवञ्च +एकस्मिन् स्थाने दोष उक्तश् चेद् अपरेष्व् अपि स्थानेषु तादृशा दोषास् स्वतः परिष्करणीयाः खलु (तत्र "वर्णद्वयान्वेषणम्" इत्य् उपायोऽपि सरलो दर्शितः) …।

2024-01-30 00:40 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +शान्तिहोमप्रयोगः ॥ कर्ता कृतसर्वाङ्गवपनो नद्यादौ स्नात्वा ग्रामश्मशानयोर्मध्ये शुचौ देशे प्राङ्मुख उपविश्य पवित्रपाणिराचम्य प्राणानायम्य देशकालौ सङ्कीर्त्य ( यज्ञोपवीत्येव ) ज्ञातीनां मम च सर्वेषामघन
कार्यबाहुल्यात्  ह्यः केवलं‌ "अस्थिसञ्चयनविधिं‌"  (11_asthisanchayanavidhiH.md)
इत्यत्र विद्यमानं‌ उद्धरणचिह्नं केवलं‌ समीकृतवानस्मि । अग्रिमं इतोऽपि न दृष्टवानस्मि। अद्य करोमि।

2024-01-30 00:43 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +शान्तिहोमप्रयोगः ॥ कर्ता कृतसर्वाङ्गवपनो नद्यादौ स्नात्वा ग्रामश्मशानयोर्मध्ये शुचौ देशे प्राङ्मुख उपविश्य पवित्रपाणिराचम्य प्राणानायम्य देशकालौ सङ्कीर्त्य ( यज्ञोपवीत्येव ) ज्ञातीनां मम च सर्वेषामघन
11_asthisanchayanavidhiH.md अस्मिन्पृष्ठे अपि प्रमादात् कुत्रापि दोषाः‌ स्युः‌ ।  दोषाः‌ सन्ति चेत् कृपया सुचयतु।

2024-01-30 00:51 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +इति ॥ ( बो. पि. सू. २. ४. १८-१९ ) यथो एतत् गृहानेष्यन्नुपकल्पयत इति स्वान् स्वान् गृहस्थधर्मान्प्रतिपत्स्यान्नित्येवेदमुक्तं भवति । नाऽशुचिः काम्यं तप आतिष्ठेन्न यजेन्न स्वाध्यायमधीयीतान्यत्राग्निहोत
![Screenshot from 2024-01-30 06-20-38](https://github.com/vishvAsa/vedAH_yajuH/assets/156443341/5a940653-b549-42b2-a132-7dae98a2bcce)

2024-01-30 01:00 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +इति ॥ ( बो. पि. सू. २. ४. १८-१९ ) यथो एतत् गृहानेष्यन्नुपकल्पयत इति स्वान् स्वान् गृहस्थधर्मान्प्रतिपत्स्यान्नित्येवेदमुक्तं भवति । नाऽशुचिः काम्यं तप आतिष्ठेन्न यजेन्न स्वाध्यायमधीयीतान्यत्राग्निहोत
नैवम् - मूलस्य चित्रम् प्रार्थितम् - भवतोट्टङ्कितं तु चित्रं विना द्रष्टुं शक्नोमीह।

2024-01-30 01:01 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +शान्तिहोमप्रयोगः ॥ कर्ता कृतसर्वाङ्गवपनो नद्यादौ स्नात्वा ग्रामश्मशानयोर्मध्ये शुचौ देशे प्राङ्मुख उपविश्य पवित्रपाणिराचम्य प्राणानायम्य देशकालौ सङ्कीर्त्य ( यज्ञोपवीत्येव ) ज्ञातीनां मम च सर्वेषामघन
अस्तु - अवशिष्टय् अपि परीक्ष्य सूचयतु।

2024-01-30 01:05 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +इति ॥ ( बो. पि. सू. २. ४. १८-१९ ) यथो एतत् गृहानेष्यन्नुपकल्पयत इति स्वान् स्वान् गृहस्थधर्मान्प्रतिपत्स्यान्नित्येवेदमुक्तं भवति । नाऽशुचिः काम्यं तप आतिष्ठेन्न यजेन्न स्वाध्यायमधीयीतान्यत्राग्निहोत
![Screenshot from 2024-01-30 06-35-11](https://github.com/vishvAsa/vedAH_yajuH/assets/156443341/53a09fe6-0f81-42f6-af3d-89895b96792f)

2024-01-30 01:07 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +दशमदिनप्रयोगः॥ कर्ता स्नात्वा नित्यपिण्डदानादिकं प्रातःसायं करिष्यमाणं समानतन्त्रेण निर्वर्त्य पिण्डौ सुरक्षितं स्थापयेत् । प्रभूतबल्यर्थमाज्यं दधि मधु क्षीरं कार्पासं वस्त्रमुपवीतं पिष्टमयछत्रपादुके
अपि चोद्धरणं नेदं कुतः?
कुत्र इति नावगतम् ।

2024-01-30 01:13 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +इति ॥ ( बो. पि. सू. २. ४. १८-१९ ) यथो एतत् गृहानेष्यन्नुपकल्पयत इति स्वान् स्वान् गृहस्थधर्मान्प्रतिपत्स्यान्नित्येवेदमुक्तं भवति । नाऽशुचिः काम्यं तप आतिष्ठेन्न यजेन्न स्वाध्यायमधीयीतान्यत्राग्निहोत
वीक्षताम् - प्रतिपत्स्यन्न् इत्यस्ति, न तु प्रतिपत्स्यान्न् इति।  एवञ्चोद्धरणम् अधिगत्य विन्यसनीयम् -

```
"यथो एतत् गृहानेष्यन्नुपकल्पयत" इति  
"स्वान् स्वान् गृहस्थधर्मान्प्रतिपत्स्यन्नि"त्येवेदमुक्तं भवति ।  
नाऽशुचिः काम्यं तप आतिष्ठेन्न यजेन्न स्वाध्यायमधीयीतान्यत्राग्निहोत्रदर्शपूर्णमासाभ्यां न दद्यात्काममृत्विग्भ्यो दद्यात् ।
```

2024-01-30 01:13 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +शान्तिहोमप्रयोगः ॥ कर्ता कृतसर्वाङ्गवपनो नद्यादौ स्नात्वा ग्रामश्मशानयोर्मध्ये शुचौ देशे प्राङ्मुख उपविश्य पवित्रपाणिराचम्य प्राणानायम्य देशकालौ सङ्कीर्त्य ( यज्ञोपवीत्येव ) ज्ञातीनां मम च सर्वेषामघन
![Screenshot from 2024-01-30 06-42-20](https://github.com/vishvAsa/vedAH_yajuH/assets/156443341/8114c1d4-cff5-4dfa-be91-79170754ec5a)

2024-01-30 01:15 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +शान्तिहोमप्रयोगः ॥ कर्ता कृतसर्वाङ्गवपनो नद्यादौ स्नात्वा ग्रामश्मशानयोर्मध्ये शुचौ देशे प्राङ्मुख उपविश्य पवित्रपाणिराचम्य प्राणानायम्य देशकालौ सङ्कीर्त्य ( यज्ञोपवीत्येव ) ज्ञातीनां मम च सर्वेषामघन
अत्र उद्धरणचिह्नं "कर्ता कृतसर्वाङ्गवपनो ............करिष्ये" एतावत्पर्यन्तं दातव्यं‌ वा‌?

2024-01-30 01:16 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +दशमदिनप्रयोगः॥ कर्ता स्नात्वा नित्यपिण्डदानादिकं प्रातःसायं करिष्यमाणं समानतन्त्रेण निर्वर्त्य पिण्डौ सुरक्षितं स्थापयेत् । प्रभूतबल्यर्थमाज्यं दधि मधु क्षीरं कार्पासं वस्त्रमुपवीतं पिष्टमयछत्रपादुके
सञ्चिकानाम, पङ्क्तिसङ्ख्या तु स्पष्टे चेति मन्ये। 'तिलोदकमुपतिष्ठतु' इत्य् उद्धरणम्, उपतिष्ठतेति वाक्यान्तरम् अप्य् उद्धरणम् ।

2024-01-30 01:18 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +शान्तिहोमप्रयोगः ॥ कर्ता कृतसर्वाङ्गवपनो नद्यादौ स्नात्वा ग्रामश्मशानयोर्मध्ये शुचौ देशे प्राङ्मुख उपविश्य पवित्रपाणिराचम्य प्राणानायम्य देशकालौ सङ्कीर्त्य ( यज्ञोपवीत्येव ) ज्ञातीनां मम च सर्वेषामघन
नैव - ज्ञातीनाम् इत्य् आरभ्य खलु । यजमानः किं वदति, किं करोतीति विवेक्तव्यं स्पष्टतायै।

2024-01-30 01:29 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +दशमदिनप्रयोगः॥ कर्ता स्नात्वा नित्यपिण्डदानादिकं प्रातःसायं करिष्यमाणं समानतन्त्रेण निर्वर्त्य पिण्डौ सुरक्षितं स्थापयेत् । प्रभूतबल्यर्थमाज्यं दधि मधु क्षीरं कार्पासं वस्त्रमुपवीतं पिष्टमयछत्रपादुके
![Screenshot from 2024-01-30 06-57-32](https://github.com/vishvAsa/vedAH_yajuH/assets/156443341/40d3f264-052c-42d7-8584-835d0a383549)

2024-01-30 01:33 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +शान्तिहोमप्रयोगः ॥ कर्ता कृतसर्वाङ्गवपनो नद्यादौ स्नात्वा ग्रामश्मशानयोर्मध्ये शुचौ देशे प्राङ्मुख उपविश्य पवित्रपाणिराचम्य प्राणानायम्य देशकालौ सङ्कीर्त्य ( यज्ञोपवीत्येव ) ज्ञातीनां मम च सर्वेषामघन
अस्तु कृतवानस्मि

2024-01-30 03:45 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +दशमदिनप्रयोगः॥ कर्ता स्नात्वा नित्यपिण्डदानादिकं प्रातःसायं करिष्यमाणं समानतन्त्रेण निर्वर्त्य पिण्डौ सुरक्षितं स्थापयेत् । प्रभूतबल्यर्थमाज्यं दधि मधु क्षीरं कार्पासं वस्त्रमुपवीतं पिष्टमयछत्रपादुके
किम् अत्र चित्रप्रेणनेन विवक्षितम्??

2024-01-30 06:22 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +दशमदिनप्रयोगः॥ कर्ता स्नात्वा नित्यपिण्डदानादिकं प्रातःसायं करिष्यमाणं समानतन्त्रेण निर्वर्त्य पिण्डौ सुरक्षितं स्थापयेत् । प्रभूतबल्यर्थमाज्यं दधि मधु क्षीरं कार्पासं वस्त्रमुपवीतं पिष्टमयछत्रपादुके
उपतिष्ठतः ?? पुनः परीक्षताम्। संशयास्पदम्। अपि चोद्धरणं नेदं कुतः?

अहं‌ चिन्तितवान् मत्कृते (उद्धरणचिह्ने) कार्ये दोषः‌ अस्ति इति अतः चित्रमिदं‌ प्रेषितवान् । दोषः कुत्र इति न ज्ञातवान् ।

2024-01-31 01:44 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +दशमदिनप्रयोगः॥ कर्ता स्नात्वा नित्यपिण्डदानादिकं प्रातःसायं करिष्यमाणं समानतन्त्रेण निर्वर्त्य पिण्डौ सुरक्षितं स्थापयेत् । प्रभूतबल्यर्थमाज्यं दधि मधु क्षीरं कार्पासं वस्त्रमुपवीतं पिष्टमयछत्रपादुके
(ह्यः टॆलिग्रामि स्पष्टीकृतम्। )

2024-01-31 16:35 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +दशमदिनप्रयोगः॥ कर्ता स्नात्वा नित्यपिण्डदानादिकं प्रातःसायं करिष्यमाणं समानतन्त्रेण निर्वर्त्य पिण्डौ सुरक्षितं स्थापयेत् । प्रभूतबल्यर्थमाज्यं दधि मधु क्षीरं कार्पासं वस्त्रमुपवीतं पिष्टमयछत्रपादुके
आम् ज्ञातवानस्मि।

2024-01-31 16:37 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +इति ॥ ( बो. पि. सू. २. ४. १८-१९ ) यथो एतत् गृहानेष्यन्नुपकल्पयत इति स्वान् स्वान् गृहस्थधर्मान्प्रतिपत्स्यान्नित्येवेदमुक्तं भवति । नाऽशुचिः काम्यं तप आतिष्ठेन्न यजेन्न स्वाध्यायमधीयीतान्यत्राग्निहोत
सत्यम् ।  समीकृतमस्ति ।

2024-02-01 00:54 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +इति ॥ ( बो. पि. सू. २. ४. १८-१९ ) यथो एतत् गृहानेष्यन्नुपकल्पयत इति स्वान् स्वान् गृहस्थधर्मान्प्रतिपत्स्यान्नित्येवेदमुक्तं भवति । नाऽशुचिः काम्यं तप आतिष्ठेन्न यजेन्न स्वाध्यायमधीयीतान्यत्राग्निहोत
न हि - यथादर्शितं न समीकृतम्। यथापूर्वम् एवास्ति।

2024-02-01 00:58 UTC, vvasuki requested changes

2024-02-01 00:58 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +इति मध्ये पश्चिमे पूर्वे 'अयं पिण्ड उपतिष्ठतु' इति दधिमधुक्षीरसर्पिस्तिलमिश्रांस्त्रीन्पिण्डान्दत्वा तदुपरि पूर्ववत्तिलोदकं दद्यात् । "अथाऽञ्जनमुपतिष्ठतु", अभ्यननं॰, वासः॰,इत्यञ्जनाभ्यञ्जनवासांसि दत्
अत्राप्य् उद्धरणांशस् टॆलिग्रामि भवता ऽभिज्ञातस् तद्रीत्या न दर्शितः।

2024-02-01 00:58 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +इति सङ्कल्प्य स्थण्डिलोल्लेखनादि लौकिकाऽग्निमुपसमाधाय, शान्तिहोमः कर्म, अपूर्वं तन्त्रं, पवमानो नामाऽग्निः अग्निर्मृत्युश्च देवता, नवं सर्पिर्हविः, सद्यो यक्ष्ये, इत्यन्वाधानाद्याग्निं परिस्तीर्य, उत
इयं सञ्चिका पुनः परीक्षणीया +उद्धरणाभिज्ञानदृष्ट्या। एवञ्च, यावत्यः पङ्क्तय एतावत् स्पृष्टाः, तासु यावद् निर्दुष्टता नाङ्गीकृता, तावन् नूतन पङ्क्तीनां शोधने नानुवर्तताम्।

2024-02-01 05:56 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +इति मध्ये पश्चिमे पूर्वे 'अयं पिण्ड उपतिष्ठतु' इति दधिमधुक्षीरसर्पिस्तिलमिश्रांस्त्रीन्पिण्डान्दत्वा तदुपरि पूर्ववत्तिलोदकं दद्यात् । "अथाऽञ्जनमुपतिष्ठतु", अभ्यननं॰, वासः॰,इत्यञ्जनाभ्यञ्जनवासांसि दत्
इदानीं सम्यक् कृतं वा इति पश्यतु।

2024-02-01 05:59 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +इति सङ्कल्प्य स्थण्डिलोल्लेखनादि लौकिकाऽग्निमुपसमाधाय, शान्तिहोमः कर्म, अपूर्वं तन्त्रं, पवमानो नामाऽग्निः अग्निर्मृत्युश्च देवता, नवं सर्पिर्हविः, सद्यो यक्ष्ये, इत्यन्वाधानाद्याग्निं परिस्तीर्य, उत
एकवारं‌ पश्यतु । सम्यक् कृतं वा इति।

2024-02-01 06:08 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +इति ॥ ( बो. पि. सू. २. ४. १८-१९ ) यथो एतत् गृहानेष्यन्नुपकल्पयत इति स्वान् स्वान् गृहस्थधर्मान्प्रतिपत्स्यान्नित्येवेदमुक्तं भवति । नाऽशुचिः काम्यं तप आतिष्ठेन्न यजेन्न स्वाध्यायमधीयीतान्यत्राग्निहोत
अत्रोत्तरं न लब्धम्।

2024-02-01 06:15 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +इति ॥ ( बो. पि. सू. २. ४. १८-१९ ) यथो एतत् गृहानेष्यन्नुपकल्पयत इति स्वान् स्वान् गृहस्थधर्मान्प्रतिपत्स्यान्नित्येवेदमुक्तं भवति । नाऽशुचिः काम्यं तप आतिष्ठेन्न यजेन्न स्वाध्यायमधीयीतान्यत्राग्निहोत
पुनः कृतवानस्मि पश्यतु।

2024-02-01 07:07 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +इति ॥ ( बो. पि. सू. २. ४. १८-१९ ) यथो एतत् गृहानेष्यन्नुपकल्पयत इति स्वान् स्वान् गृहस्थधर्मान्प्रतिपत्स्यान्नित्येवेदमुक्तं भवति । नाऽशुचिः काम्यं तप आतिष्ठेन्न यजेन्न स्वाध्यायमधीयीतान्यत्राग्निहोत
न कृतम् एव। उपरि मया दिनद्वयात् पूर्वं कथम् प्रस्तोतव्यम् इति स्पष्टम् एव दर्शितम् ईक्षताम्।

2024-02-01 08:52 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +इति ॥ ( बो. पि. सू. २. ४. १८-१९ ) यथो एतत् गृहानेष्यन्नुपकल्पयत इति स्वान् स्वान् गृहस्थधर्मान्प्रतिपत्स्यान्नित्येवेदमुक्तं भवति । नाऽशुचिः काम्यं तप आतिष्ठेन्न यजेन्न स्वाध्यायमधीयीतान्यत्राग्निहोत
भिन्नपङ्क्तौ भवेद् वा?

2024-02-01 08:54 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +इति ॥ ( बो. पि. सू. २. ४. १८-१९ ) यथो एतत् गृहानेष्यन्नुपकल्पयत इति स्वान् स्वान् गृहस्थधर्मान्प्रतिपत्स्यान्नित्येवेदमुक्तं भवति । नाऽशुचिः काम्यं तप आतिष्ठेन्न यजेन्न स्वाध्यायमधीयीतान्यत्राग्निहोत
अत्रापि > चिह्नमिदं‌ उपयुज्यैव करणीयं‌ किम्?‌

2024-02-01 08:56 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +इति ॥ ( बो. पि. सू. २. ४. १८-१९ ) यथो एतत् गृहानेष्यन्नुपकल्पयत इति स्वान् स्वान् गृहस्थधर्मान्प्रतिपत्स्यान्नित्येवेदमुक्तं भवति । नाऽशुचिः काम्यं तप आतिष्ठेन्न यजेन्न स्वाध्यायमधीयीतान्यत्राग्निहोत
पुनः कृतवानस्मि।

2024-02-01 09:31 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> +इति ॥ ( बो. पि. सू. २. ४. १८-१९ ) यथो एतत् गृहानेष्यन्नुपकल्पयत इति स्वान् स्वान् गृहस्थधर्मान्प्रतिपत्स्यान्नित्येवेदमुक्तं भवति । नाऽशुचिः काम्यं तप आतिष्ठेन्न यजेन्न स्वाध्यायमधीयीतान्यत्राग्निहोत
अधुना सम्यग् दृश्यते। पङ्क्तिभेदे नास्त्याग्रहः - अस्ति चेच् चिन्ता नास्ति, नास्ति चेद् अपि चिन्ता नास्ति।

2024-02-01 09:39 UTC, vvasuki requested changes
14_vRShotsargavidhiH.md इत्यस्मिन् स्पृष्टासु पङ्क्तीषु पुनः परीक्ष्य वदतु।

2024-02-01 09:39 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> + अग्नये मृत्यव इदं॰ ॥अथ द्वादश स्रुवाहुतीर्जुहोति-"अप नः शोशुचद्घगमग्ने शुशुध्या रयिम् । अप नः शोशुचदघँ स्वाहा । ( अग्नय इदं॰, इति सर्वत्र त्यागः) । सुक्षेत्रिया सुगातुया वसूया च यजामहे । अप नः शोशुच
अत्रोद्धरण-दर्शनं न समञ्जसम्। 
"अग्नये मृत्यव इदं॰" इत्यादीनि त्यागवाक्यान्य् उच्यन्त इति तान्य् अप्य् उद्धरणानि।  
अपि च दीर्घोद्धरणनयो ऽनुसरणीयो भाति।

2024-02-01 10:00 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> + अग्नये मृत्यव इदं॰ ॥अथ द्वादश स्रुवाहुतीर्जुहोति-"अप नः शोशुचद्घगमग्ने शुशुध्या रयिम् । अप नः शोशुचदघँ स्वाहा । ( अग्नय इदं॰, इति सर्वत्र त्यागः) । सुक्षेत्रिया सुगातुया वसूया च यजामहे । अप नः शोशुच
इदानीं कृतमस्ति । सम्यगस्ति वा न वा इति सूचयतु

2024-02-01 14:27 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> + अग्नये मृत्यव इदं॰ ॥अथ द्वादश स्रुवाहुतीर्जुहोति-"अप नः शोशुचद्घगमग्ने शुशुध्या रयिम् । अप नः शोशुचदघँ स्वाहा । ( अग्नय इदं॰, इति सर्वत्र त्यागः) । सुक्षेत्रिया सुगातुया वसूया च यजामहे । अप नः शोशुच
![Screenshot from 2024-02-01 19-56-54](https://github.com/vishvAsa/vedAH_yajuH/assets/156443341/0ac97870-3829-487b-b4bd-cadd0c9a1a0b)
![Uploading Screenshot from 2024-02-01 19-56-59.png…]()

2024-02-02 01:39 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> + अग्नये मृत्यव इदं॰ ॥अथ द्वादश स्रुवाहुतीर्जुहोति-"अप नः शोशुचद्घगमग्ने शुशुध्या रयिम् । अप नः शोशुचदघँ स्वाहा । ( अग्नय इदं॰, इति सर्वत्र त्यागः) । सुक्षेत्रिया सुगातुया वसूया च यजामहे । अप नः शोशुच
आम्

2024-02-02 03:48 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> + अग्नये मृत्यव इदं॰ ॥अथ द्वादश स्रुवाहुतीर्जुहोति-"अप नः शोशुचद्घगमग्ने शुशुध्या रयिम् । अप नः शोशुचदघँ स्वाहा । ( अग्नय इदं॰, इति सर्वत्र त्यागः) । सुक्षेत्रिया सुगातुया वसूया च यजामहे । अप नः शोशुच
![Screenshot from 2024-02-01 19-56-59](https://github.com/vishvAsa/vedAH_yajuH/assets/156443341/11489eda-a58c-48ce-9b38-827306e4e9a2)

कुत्र दोषः‌ अस्ति

2024-02-02 08:31 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/14_vRShotsargavidhiH.md
> +१. हुतशेषनिधानं‌ गृह्यकारिकायामुक्तम् ।।
इयम् पादटिप्पनीति भाति ।  https://sanskrit.github.io/groups/dyuganga/projects/text/proofreading/editing/markdown/Footnotes/ इत्य् अनुसृत्य विन्यस्यतु। सन्देहे सति टॆलिग्रामि पृच्छतु। 

तद् विधाय, "पाथः" इति शब्दम् पूर्ववर्त्युद्धरणांशेन योजयतु।

2024-02-02 13:52 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/14_vRShotsargavidhiH.md
> +१. हुतशेषनिधानं‌ गृह्यकारिकायामुक्तम् ।।
कृतमस्ति। सम्यगस्ति वा न वा इति सूचयतु।

2024-02-02 13:57 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/12_dashamadinavidhiH.md
> + अग्नये मृत्यव इदं॰ ॥अथ द्वादश स्रुवाहुतीर्जुहोति-"अप नः शोशुचद्घगमग्ने शुशुध्या रयिम् । अप नः शोशुचदघँ स्वाहा । ( अग्नय इदं॰, इति सर्वत्र त्यागः) । सुक्षेत्रिया सुगातुया वसूया च यजामहे । अप नः शोशुच
मूले यथा अस्ति तथैव कृतमस्ति ननु?

2024-02-02 14:18 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/14_vRShotsargavidhiH.md
> +१. हुतशेषनिधानं‌ गृह्यकारिकायामुक्तम् ।।
![image](https://github.com/vishvAsa/vedAH_yajuH/assets/2664797/793fd0b9-6946-4c39-acb9-b702109d2e13)

इति वर्तमानं सावधानम् अवलोकयतु। तत्र Ref इति स्थाने दृश्यमानपदस्यान्ते [^१] इति स्थापनीयम्। न स्थापितम् । 
पुनः पादटिप्पन्याः निर्वचनम् एवम् पृथक् पङ्क्तौ `[^१]:` इति प्रारभेत, "Ref"स्थानसमीपे, न तु दूरे। अन्यथा, अन्यत्र च दृश्यते। 


परिष्करोतु।

2024-02-02 15:25 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/14_vRShotsargavidhiH.md
> +१. हुतशेषनिधानं‌ गृह्यकारिकायामुक्तम् ।।
कृतवानस्मि साधु कृतं वा इति पुनः परीक्ष्यताम् ।

2024-02-03 01:33 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/14_vRShotsargavidhiH.md
> +[१]: हुतशेषनिधानं‌ गृह्यकारिकायामुक्तम् ।।
सुकृतम्। पादटिप्पनीपङ्क्तेर् अस्याः पूर्वं त्व् एका रिक्ता पङ्क्तिः (empty line) निवेशनीया

2024-02-03 03:44 UTC, Vidyadharbhat commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/4_pitRmedhakANDam/14_vRShotsargavidhiH.md
> +[१]: हुतशेषनिधानं‌ गृह्यकारिकायामुक्तम् ।।
कृतमस्ति

2024-02-03 04:21 UTC, vvasuki commented
सुकृतम्। इत्थं भवतः प्रथमपरिष्करणगुच्छं सुसम्पन्नम्, भवांश् च निपुणतरः संवृत्तः। अग्रे ऽनुवर्तताम् उक्तासु सञ्चिकासु।

2024-02-03 04:21 UTC, merged