Content
vishvAsa/vedAH_yajuH pull request #385
Opened 2024-03-30 19:59 UTC by Shweta800525

2024-03-31 01:31 UTC, vvasuki requested changes

2024-03-31 01:31 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +अष्टोत्तरशतं वाथ ह्यष्टाविन्शतिमेव वा ।
ह्यष्टाविन्शतिमेव इति दुष्टम्। पूर्वम् एव सम्यग् आसीत्।

2024-03-31 01:31 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +त्रि ँशद्धाम विराजति वातपङ्गाय शिश्रिये ।
#ँ-चिह्नात् पूर्वं रिक्तस्थानम् (space) न स्यात्। एवम् अन्यत्रापि परीक्ष्य समीकरणीयम्

2024-03-31 16:48 UTC, Shweta800525 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +अष्टोत्तरशतं वाथ ह्यष्टाविन्शतिमेव वा ।
done sir

2024-03-31 16:48 UTC, Shweta800525 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +त्रि ँशद्धाम विराजति वातपङ्गाय शिश्रिये ।
done sir

2024-04-16 08:16 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +> आश्लेषासर्वपादेषु शान्तिः कार्या प्रयत्नतः ।
ऊर्ध्वम् एका रिक्ता पङ्क्तिर् अपेक्ष्यते। यथाऽत्र दर्शितम् - https://sanskrit.github.io/groups/dyuganga/projects/text/proofreading/editing/markdown/Quotes/

2024-04-16 08:16 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +"मानवानां हितार्थाय मनुना सर्वकामिकम् ।
"-चिह्नम् अत्र कुतः?

2024-04-16 08:16 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +(बो. गृ. शे. सू. ६. ३)आश्लेषायान्तु जातानां शान्तिं वक्ष्याम्यतः परम् ।
"आश्लेषायान्तु जातानां शान्तिं वक्ष्याम्यतः परम् ।" इत्यप्य् उद्धरणस्याङ्गम् - श्लोकार्धं तत्।

2024-04-19 07:16 UTC, Shweta800525 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +(बो. गृ. शे. सू. ६. ३)आश्लेषायान्तु जातानां शान्तिं वक्ष्याम्यतः परम् ।
जी सर,हमने सही कर दिया।

2024-04-19 08:13 UTC, vvasuki reviewed
बहवो दोषाः। पुनः प्रत्येकाम् पङ्क्तिम्  परीक्ष्य , परिष्कृत्य, प्रतिसूत्रम् उत्तरं लिखित्वा सूचयतु।

2024-04-19 08:13 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +आ 'जिघ्रेति' च मन्त्रेण कलशस्थापनं शुभम् ॥
`'` इति कुतः? `'आ जिघ्रे'ति` इति चिकीर्षितम्?

2024-04-19 08:13 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +> अर्यमणं॰ (१) भगं॰ (२) सवितारं॰ (३) त्वष्टार॰ (४) वायु॰ (५) इन्द्राग्नी॰ (६) मित्रं०  (७) इन्द्र॰ (८) निऋर्तिं० (९) अपः० (१०) विश्वान्देवान्०   (११) विष्णुं॰ (१२) वसून्॰ (१३) वरुणं० (१४) अजमेकपादंं॰
“>"-चिह्नप्रयोगपक्षे, उद्धरण-भागस्यादाव् अन्ते च रिक्तपङ्क्तिस् (empty line) स्याद् एव।

एवं सर्वत्र परिष्कार्यम्।

2024-04-19 08:13 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> + प्रधानदेवतासूक्तस्थाने सर्पसूक्तम्--
पङ्क्तीनाम् प्रारम्भे रिक्तस्थानम् (` `) न स्यात्।

2024-04-19 08:13 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +इत्युक्तं सर्पशान्त्यर्थ सारमागमचोदितम् ॥
इमाम् प्रङ्क्तिम् पुनः परीक्षताम्। दोषो ऽस्ति।

2024-04-19 08:13 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +>
एतत् किमर्थम्?

2024-04-19 08:13 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +> दक्षिणे – बृहस्पतिः प्रथमं० तिव्यः पुरस्तात्०
`दक्षिणे -` इति कथम् उद्धरणाङ्गम्?

2024-04-19 08:13 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +>  सद्योजातादिपञ्चदेवताः, वरुणञ्चाबाह्य षोडशोपचारैः पूजयेत् । आचार्यादयः कुम्भमन्वारभ्य पूर्ववदुद्रैकादशिन्यादि जपेयुः ।
इदं कथम् उद्धरणम्?

2024-04-19 08:13 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +>नमो अस्तु सर्पेम्यो ये के च पृथिवीमनु ।
`>` → `> ` (रिक्तावकाशसहितम् भवेत्। )

एवम् अन्यत्र परिष्करणीयम्।

2024-04-19 08:13 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +>पितृभ्यश्च पक्कहोमः।
पुनः परीक्षताम् - दोषोऽस्ति।

2024-04-19 08:13 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +>अथ बृहस्पतिसूक्तम् आ वेधसं नीलपृष्ठं बृहन्तम् ।
अथ बृहस्पतिसूक्तम्

इति कथम् उद्धरणाङ्गम्?

2024-04-19 17:57 UTC, Shweta800525 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +आ 'जिघ्रेति' च मन्त्रेण कलशस्थापनं शुभम् ॥
जिघ्रेति मन्त्र होने के वजह से लगाया गया था।

2024-04-19 18:02 UTC, Shweta800525 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +>
सर हमने बस यही तक किया था ताकि जो गलत हो वो जाना जा सके।
इसके आगे से करना बाकि था जो की अब किया जाएगा।

2024-04-19 19:15 UTC, Shweta800525 reviewed
सर हमने file का review है और
निर्देशानुसार कार्य करने का प्रयास किया है।

2024-04-20 00:45 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +आ 'जिघ्रेति' च मन्त्रेण कलशस्थापनं शुभम् ॥
इति-शब्दस् तु मन्त्रो नास्ति। अतः, "ति" इति वर्णो नोद्धरणे स्यात्।

2024-04-20 00:46 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +>
परिहृत्य वदतु।

2024-04-20 00:47 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +"मानवानां हितार्थाय मनुना सर्वकामिकम् ।
तर्हि मनोः कथनं किम्? तद् एवोद्धरण-रीत्या दर्शनीयम्।

2024-04-20 08:14 UTC, Shweta800525 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +> दक्षिणे – बृहस्पतिः प्रथमं० तिव्यः पुरस्तात्०
मूल प्रति मे है।
सहि कर दिया गया है।

2024-04-20 08:18 UTC, Shweta800525 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +>  सद्योजातादिपञ्चदेवताः, वरुणञ्चाबाह्य षोडशोपचारैः पूजयेत् । आचार्यादयः कुम्भमन्वारभ्य पूर्ववदुद्रैकादशिन्यादि जपेयुः ।
सही कर दिया गया है।

2024-04-20 08:19 UTC, Shweta800525 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +>नमो अस्तु सर्पेम्यो ये के च पृथिवीमनु ।
सही कर दिया गया है।

2024-04-20 08:20 UTC, Shweta800525 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +>पितृभ्यश्च पक्कहोमः।
सही कर दिया गया है।

2024-04-20 08:22 UTC, Shweta800525 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +>अथ बृहस्पतिसूक्तम् आ वेधसं नीलपृष्ठं बृहन्तम् ।
layout के वजह से लगाया गया है।

2024-04-20 08:29 UTC, Shweta800525 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +"मानवानां हितार्थाय मनुना सर्वकामिकम् ।
जी सर हटा दिया है।

2024-04-20 08:31 UTC, Shweta800525 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +आ 'जिघ्रेति' च मन्त्रेण कलशस्थापनं शुभम् ॥
मूल प्रति मे लिखा हुआ है।

2024-04-20 08:32 UTC, Shweta800525 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +> अर्यमणं॰ (१) भगं॰ (२) सवितारं॰ (३) त्वष्टार॰ (४) वायु॰ (५) इन्द्राग्नी॰ (६) मित्रं०  (७) इन्द्र॰ (८) निऋर्तिं० (९) अपः० (१०) विश्वान्देवान्०   (११) विष्णुं॰ (१२) वसून्॰ (१३) वरुणं० (१४) अजमेकपादंं॰
सही कर दिया गया है।

2024-04-20 08:32 UTC, Shweta800525 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> + प्रधानदेवतासूक्तस्थाने सर्पसूक्तम्--
सही कर दिया गया है

2024-04-20 08:42 UTC, Shweta800525 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +इत्युक्तं सर्पशान्त्यर्थ सारमागमचोदितम् ॥
सही कर दिया गया है।

2024-04-21 00:28 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +आ 'जिघ्रेति' च मन्त्रेण कलशस्थापनं शुभम् ॥
मूले '-चिह्नम् अस्तीति? चित्रं दर्शयतु।

2024-04-21 00:28 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +इत्युक्तं सर्पशान्त्यर्थ सारमागमचोदितम् ॥
इदानीम् अप्य् असमीचीनम् अस्ति। स्वीयं संस्कृतज्ञानम् अवलम्ब्य वदतु - को दोषः?

2024-04-21 00:28 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> + प्रधानदेवतासूक्तस्थाने सर्पसूक्तम्--
न - इदामीम् अपि यथापूर्वम् एवास्ति।

2024-04-21 00:28 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +> अर्यमणं॰ (१) भगं॰ (२) सवितारं॰ (३) त्वष्टार॰ (४) वायु॰ (५) इन्द्राग्नी॰ (६) मित्रं०  (७) इन्द्र॰ (८) निऋर्तिं० (९) अपः० (१०) विश्वान्देवान्०   (११) विष्णुं॰ (१२) वसून्॰ (१३) वरुणं० (१४) अजमेकपादंं॰
न - इदामीम् अपि यथापूर्वम् एवास्ति।

2024-04-21 00:28 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +>अथ बृहस्पतिसूक्तम् आ वेधसं नीलपृष्ठं बृहन्तम् ।
न साधु। "अथ बृहस्पतिसूक्तम्" इति न +उद्धरणाङ्गम्।

2024-04-21 00:31 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +> दक्षिणे – बृहस्पतिः प्रथमं० तिव्यः पुरस्तात्०
मूले "इदम् उद्धरणम्" इति कुत्रोच्यते? चित्रं दर्शयतु। 

अपि च `.`-चिह्नं कुतो ऽत्र?

2024-04-21 00:32 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +>पितृभ्यश्च पक्कहोमः।
अधुनाऽपि वर्णदोषोऽस्ति।

2024-04-29 11:01 UTC, Shweta800525 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +आ 'जिघ्रेति' च मन्त्रेण कलशस्थापनं शुभम् ॥
चिह्न नही सर। जिघ्रेति मन्त्र का उल्लेख है इसलिए लगाया था।

2024-04-29 11:14 UTC, Shweta800525 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +> दक्षिणे – बृहस्पतिः प्रथमं० तिव्यः पुरस्तात्०
ये मन्त्र होने के वजह से quote लगाया गया है।
और चिह्न को सही कर दिया गया है।

2024-04-29 11:26 UTC, Shweta800525 commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/3_sankIrNakANDam/24_AshleShAjananashAntividhiH.md
> +>अथ बृहस्पतिसूक्तम् आ वेधसं नीलपृष्ठं बृहन्तम् ।
सही कर दिया गया है।

2024-05-03 09:57 UTC, vvasuki commented
इत्थम् उक्त्वा प्रयासोऽयम् पिनद्धः -

> सादर-प्रणामाः। संस्कृतग्रन्थशोधनार्थं पर्याप्तं भाषाज्ञानं सद्यो नास्तीति, निर्देशानुसरणं कार्यगतिश्च बहु मन्दम् इति भाति। 
तेन सद्यः कार्यम् इदं त्यजतु। पुनः कदाचिद् हिन्दी-भाषाशोधनं कार्यं चेत् प्रक्ष्यामि। 
नमस्काराः, शुभं च भूयात्। 🙏

2024-05-03 09:57 UTC, merged