Update 01_mangalAcharaNam.md
vishvAsa/vedAH_yajuH pull request #50
Opened 2022-07-29 06:05 UTC by vibhadiga

2022-07-29 06:12 UTC, vvasuki requested changes
परिष्कारास् सूचिताः। वीक्ष्य, समीकृत्य, प्रत्येकस्मिन् सूत्रे "समाहितम्" इत्य् उररीकरोतु।

2022-07-29 06:12 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +                                        * श्रीमद्भगवद्वोधायनाचार्येभ्यो नमः ॥ श्रीरस्तु *
बकारो वकारायते ऽत्र।

2022-07-29 06:12 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +श्रीमान्मङ्गलमूर्तिराशु निखिलान्विघ्नान्हरेविनगट् देवः सोऽपि महाबलो निखिलदः सिद्धिं क्रियादीप्सिताम् ।
निखिलान्विघ्नान्हरेविनगट् इत्यस्मिन् दोषो दृश्यते (निखिलान् विघ्नान् हरेद् विघराट् वेति परीक्षताम्)। न परिष्कृतं वा? अत्र सरला भाषा। अवगत्य परिष्करोतु, नावगच्छति चेत् किञ्चिट् टॆलिग्रामि पृच्छतु।

2022-07-29 06:12 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +सा चाम्बाऽखिललोकमङ्गलकरी गौरी विदध्याच्छिवं श्रीगोकर्णविभूषणाश्चिरममी(??) क्रीडन्तु नश्चेतसि ॥१॥
आह् - सन्देहस्थानं साधु सूचितम्। अमीति समीचीनम् एव। प्रश्नचिह्ने निष्कासयतु।

2022-07-29 06:12 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +                                    वाचां प्रचोदयित्री वरदां वागीश्वरीं देवीम् ॥२॥
"प्रचोदयित्रीं" इति सानुस्वारं स्यात्। अवगत्यैव शोधयतु। सन्देहे सति पृच्छतु।

2022-07-29 09:23 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +श्रीमान्मङ्गलमूर्तिराशु निखिलान्विघ्नान्हरेविनगट् देवः सोऽपि महाबलो निखिलदः सिद्धिं क्रियादीप्सिताम् ।
विघ्नराट् इति।

2022-07-29 09:24 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +सा चाम्बाऽखिललोकमङ्गलकरी गौरी विदध्याच्छिवं श्रीगोकर्णविभूषणाश्चिरममी(??) क्रीडन्तु नश्चेतसि ॥१॥
निष्कासितम्।

2022-07-29 09:25 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +                                    वाचां प्रचोदयित्री वरदां वागीश्वरीं देवीम् ॥२॥
कृतम्।
सयक् जातं वा पश्यतु एकवारम्।

2022-07-29 09:25 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +                                        * श्रीमद्भगवद्वोधायनाचार्येभ्यो नमः ॥ श्रीरस्तु *
आम्।

2022-07-29 10:00 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +श्रीमान्मङ्गलमूर्तिराशु निखिलान्विघ्नान्हरेविनगट् देवः सोऽपि महाबलो निखिलदः सिद्धिं क्रियादीप्सिताम् ।
हरेद् इति न परिष्कृतम्। पश्यतु।

2022-07-29 10:04 UTC, vvasuki reviewed
इतोऽपि परिष्कार्यम्।

2022-07-29 10:04 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +                                                         अथ मङ्गलाचरणम्
अत्र पङ्क्तिष्व् आदौ रिक्तस्थानानि मा भुवन्।

2022-07-29 10:04 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +श्रीमान्मङ्गलमूर्तिराशु निखिलान्विघ्नान्हरेविघ्नराट् देवः सोऽपि महाबलो निखिलदः सिद्धिं क्रियादीप्सिताम् ।
paragraph-सदृश-पाठखण्डात् पूर्वं रिक्ता पङ्क्तिस् स्थापनीया।

2022-07-29 10:04 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +                                 * श्रीगणेशाय नमः ॥ श्रीसरस्वत्यै नमः ॥ श्रीगुरुभ्यो नमः *
एकस्मिन्न् एव paragraph-सदृशे खण्डे पङ्क्तिभेदं दर्शयितुम् इष्टं चेत् पङ्क्तेर् अन्ते रिक्तस्थानद्वयं निवेशयेत्।  यथा - 
`* श्रीगणेशाय नमः ॥ श्रीसरस्वत्यै नमः ॥ श्रीगुरुभ्यो नमः *  ` इति।

2022-07-30 13:34 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +                                                         अथ मङ्गलाचरणम्
निष्कासितं महोदय, जातं वा न जाने

2022-07-30 13:47 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +श्रीमान्मङ्गलमूर्तिराशु निखिलान्विघ्नान्हरेविघ्नराट् देवः सोऽपि महाबलो निखिलदः सिद्धिं क्रियादीप्सिताम् ।
Enter-द्वयम्।

2022-07-30 13:49 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +                                                         अथ मङ्गलाचरणम्
सर्वेभ्यो ऽपि पङ्क्तिभ्य आदौ वर्तमानानि रिक्तस्थानानि निष्कास्येरन्। भवत्या त्व् अस्मिन्न् एव पङ्क्तौ निष्कासितानि दृश्यन्ते।

2022-07-30 13:54 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +                                                         अथ मङ्गलाचरणम्
अस्तु करोमि पुनः

2022-07-31 04:45 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +वन्दामहेऽभिवन्द्यां मन्दस्मितनिन्दितेन्दुसौन्दर्याम् ॥ वाचां प्रचोदयित्रीं वरदां वागीश्वरीं देवीम् ॥२॥
श्लोकार्धे '।' चिह्नम् एव प्रयुज्यताम्। शिष्टः श्लोकार्धो नूतनपङ्क्ताव् अस्तु।

2022-07-31 04:45 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +* श्रीमद्भगवद्बोधायनाचार्येभ्यो नमः ॥ श्रीरस्तु * श्रीमान्मङ्गलमूर्तिराशु निखिलान्विघ्नान्हरेद्विघ्नराट् देवः सोऽपि महाबलो निखिलदः सिद्धिं क्रियादीप्सिताम् । .. सा चाम्बाऽखिललोकमङ्गलकरी गौरी विदध्याच
कुतः `..` इति दृश्यते?

2022-07-31 09:23 UTC, closed without merging

2022-07-31 11:34 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +वन्दामहेऽभिवन्द्यां मन्दस्मितनिन्दितेन्दुसौन्दर्याम् ॥ वाचां प्रचोदयित्रीं वरदां वागीश्वरीं देवीम् ॥२॥
एवम् अस्तु महोदय

2022-07-31 11:43 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/01_mangalAcharaNam.md
> +* श्रीमद्भगवद्बोधायनाचार्येभ्यो नमः ॥ श्रीरस्तु * श्रीमान्मङ्गलमूर्तिराशु निखिलान्विघ्नान्हरेद्विघ्नराट् देवः सोऽपि महाबलो निखिलदः सिद्धिं क्रियादीप्सिताम् । .. सा चाम्बाऽखिललोकमङ्गलकरी गौरी विदध्याच
परिष्कृतं महोदय।