Sarvadevasamanyapuja
vishvAsa/vedAH_yajuH pull request #71
Opened 2022-09-18 16:12 UTC by vibhadiga

2022-09-28 10:52 UTC, vvasuki commented
पादटिप्पनीषु रिक्तपङ्क्तीनां रिक्तस्थानानां च विन्यासो यथा टॆलिग्रामि निर्दिष्टम्, पूर्वं च यथा कृतं, तथैव विधेयम्।

2022-10-20 08:26 UTC, vvasuki reviewed
ईषद् विन्यासे परिष्कार इष्यते  (पूर्वकृतं स्मर्तुम्  https://raw.githubusercontent.com/vishvAsa/vedAH_yajuH/content/taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/05_AchamanavidhiH.md इत्य् अवलोकयितुं शक्यम्।)

2022-10-20 08:26 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +
इमाम् अधिकां रिक्तपङ्क्तिं निष्कासयतु।

2022-10-20 08:26 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +
इमाम् अधिकां रिक्तपङ्क्तिं निष्कासयतु।

2022-10-20 08:26 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +
इमाम् अधिकां रिक्तपङ्क्तिं निष्कासयतु।

2022-10-20 08:26 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +'ॐ आगमार्थं तु देवानां गमनार्थं तु रक्षसाम् ।
ॐकारं भिन्नपङ्क्तौ स्थापयतु, येनानुष्टुभर्धपङ्क्तिः पृथक् स्यात्।

2022-10-20 08:26 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +[^२]:
अस्मादनन्तरम् एकैव रिक्ता पङ्क्तिस् स्यात्।

2022-10-21 13:31 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +
अस्तु महोदय

2022-12-28 12:29 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +
निष्कासितपङ्क्तिः

2022-12-28 12:29 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +
अत्रापि यथोक्तं कृतम्

2022-12-28 12:29 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +'ॐ आगमार्थं तु देवानां गमनार्थं तु रक्षसाम् ।
आम् महोदय स्थापितम्

2022-12-28 13:20 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +[^२]:
आम् साधु।

2022-12-28 13:21 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +[^२]:
द्वे रिक्तपङ्क्ती त्व् अधो दृश्येते निष्कासनीये (एकया रिक्तपङ्क्त्यालम्)।

2022-12-28 13:29 UTC, vvasuki requested changes

2022-12-28 13:29 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    स्वस्तिकासन-पद्मासनयोर्लक्षणम् - बालबोधे–
अधः उद्धरणम् प्रारभते। तत्र रिक्तपङ्क्तिर् एका स्यात्।

2022-12-28 13:29 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +     इति ॥
इत ऊर्ध्वं रिक्तपङ्क्तेः समाप्तिः। तत्र रिक्तपङ्क्तिर् एकास्तु।

2022-12-28 13:29 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +सुमुखश्चैकदन्तश्च कपिलो गजकर्णकः ।।
दण्डो ऽधिकः?

2022-12-28 13:29 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    अथ सक्षेपप्राणप्रतिष्ठा - अस्य श्रीप्राणप्रतिष्ठामन्त्रस्य प्राणस्थापने विनियोगः ॥ ॐ आं ह्रीं क्रों यरलवशषसहों सं हं सः मम प्राणाः । स्वाहा ॥' इति हृदयं स्पृष्ट्वा त्रिः सकृद्वा जपेत् ॥
सङ्क्षेप

2022-12-28 13:29 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
>  अथ सर्वदेवसामान्यपूजा .
अन्ते दण्डो ऽस्तु।

2022-12-28 13:29 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    > 'हस्ताभ्यामञ्जलिं बध्वाsनामिकामूलपर्वर्णोः । अड्गुष्ठौ निक्षिपेत्सेयं मुद्रा त्वावाहनी स्मृता ॥ अधोमुखी त्वियं चेत्स्यात्स्थापनी मुद्रिका स्मृता । उच्छ्रिताड्गुष्ठमुष्टयोस्तु संयोगात्सन्निधापिन
`इत्यधिकं पठन्ति ॥`

इति नोद्धरणस्याङ्गं खलु?

2022-12-28 13:29 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +   इति ध्यानम् ॥
अत्र पङ्क्तेर् आदौ न स्यू रिक्तस्थानानि

2022-12-28 13:29 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +[^22]:
पादटिप्पनेः प्राग् अस्तु रिक्ता पङ्क्तिः

2022-12-29 10:55 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    स्वस्तिकासन-पद्मासनयोर्लक्षणम् - बालबोधे–
आम् स्थापिता

2022-12-29 10:55 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +     इति ॥
स्थापिता महोदय!

2022-12-29 10:56 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +सुमुखश्चैकदन्तश्च कपिलो गजकर्णकः ।।
समीकृतम्

2022-12-29 10:56 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    अथ सक्षेपप्राणप्रतिष्ठा - अस्य श्रीप्राणप्रतिष्ठामन्त्रस्य प्राणस्थापने विनियोगः ॥ ॐ आं ह्रीं क्रों यरलवशषसहों सं हं सः मम प्राणाः । स्वाहा ॥' इति हृदयं स्पृष्ट्वा त्रिः सकृद्वा जपेत् ॥
आम्, सम्यक् कृतम्

2022-12-29 10:56 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
>  अथ सर्वदेवसामान्यपूजा .
स्थापितः

2022-12-29 10:57 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    > 'हस्ताभ्यामञ्जलिं बध्वाsनामिकामूलपर्वर्णोः । अड्गुष्ठौ निक्षिपेत्सेयं मुद्रा त्वावाहनी स्मृता ॥ अधोमुखी त्वियं चेत्स्यात्स्थापनी मुद्रिका स्मृता । उच्छ्रिताड्गुष्ठमुष्टयोस्तु संयोगात्सन्निधापिन
नैव, नोद्धरणाङ्गम्

2022-12-29 10:58 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +   इति ध्यानम् ॥
सम्यक् कृतम्

2022-12-29 10:58 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +[^22]:
अस्तु महोदय

2022-12-29 10:58 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    > 'हस्ताभ्यामञ्जलिं बध्वाsनामिकामूलपर्वर्णोः । अड्गुष्ठौ निक्षिपेत्सेयं मुद्रा त्वावाहनी स्मृता ॥ अधोमुखी त्वियं चेत्स्यात्स्थापनी मुद्रिका स्मृता । उच्छ्रिताड्गुष्ठमुष्टयोस्तु संयोगात्सन्निधापिन
तर्ह्य् उद्धरणखण्डाद् बहिर् भिन्नपङ्क्तौ भवेत्।

2022-12-29 11:00 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    > 'हस्ताभ्यामञ्जलिं बध्वाsनामिकामूलपर्वर्णोः । अड्गुष्ठौ निक्षिपेत्सेयं मुद्रा त्वावाहनी स्मृता ॥ अधोमुखी त्वियं चेत्स्यात्स्थापनी मुद्रिका स्मृता । उच्छ्रिताड्गुष्ठमुष्टयोस्तु संयोगात्सन्निधापिन
Astu

2022-12-29 12:04 UTC, vvasuki requested changes

2022-12-29 12:04 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +[^२]:
अत्र १०९ इति पङ्क्तेः परम् एका रिक्ता पङ्क्तिर् भवतु। १११ इति पङ्क्तेः प्राग् अपि।

2022-12-29 12:04 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> -117
भविष्य एतादृश्शीः pdf-पृष्ठ-सङ्ख्या रक्षतु  `[[117]]` इति कृत्वा। (किञ्चैतद् अवधेयम् - मूले paragraph-मध्ये श्लोकमध्ये वा नूतनपृष्ठारम्भस् स्यात्। तर्हि मध्ये पृष्ठसङ्ख्या निपतेत्। अस्मत्संस्करणे तद् वारणीयम्। pargraph-आदि-विच्छेदो यथा न स्यात् तथा पृष्ठसङ्ख्याम् इषच् चालयित्वा स्थापणीयम्। ताः सङ्ख्याः pagagraph मध्ये न स्युः, वाक्यमध्ये नैव, पदमध्ये नैव। )

2022-12-30 07:04 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> -117
तथैव भवतु महोदय

2022-12-30 08:24 UTC, vvasuki requested changes

2022-12-30 08:24 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    | १ शिवः<br>२ विष्णुः ३ रविः<br>   १ शिवः<br>५ देवी  ४ गणेशः 	| २ विष्णुः<br>२ शिवः ३ गणेशः<br>   १ विष्णुः<br>५ देवी  ४ रविः 	| ३ रविः<br>२ शिवः ३ गणेशः<br>    १ रविः<br>५ देवी  ४ विष्णुः 	| ४ द
किञ्चिद् अत्र विचित्रम्। तालिकेष्टा? (Table)

2022-12-30 08:24 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +     इति पूजापङ्कजभास्करे ॥
उद्धरणात् परम् (इतिकारात् पूर्वम्) इष्यते रिक्ता पङ्क्तिः।

2022-12-30 08:24 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    इति शङ्खपूजाकर्तव्यपरम् ॥
उद्धरणात् परम् (इतिकारात् पूर्वम्) इष्यते रिक्ता पङ्क्तिः।

2022-12-30 08:24 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +     इति बालबोधे ।।
उद्धरणात् परम् (इतिकारात् पूर्वम्) इष्यते रिक्ता पङ्क्तिः।

2022-12-30 08:24 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    इदं महाभिषेकफलपरम् ॥
उद्धरणात् परम् इष्यते रिक्ता पङ्क्तिः।

2022-12-30 08:24 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +[^15]:
पादटिप्पनेः पूर्वम् भवेद् रिक्ता पङ्क्तिः

2022-12-30 08:36 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    | १ शिवः<br>२ विष्णुः ३ रविः<br>   १ शिवः<br>५ देवी  ४ गणेशः 	| २ विष्णुः<br>२ शिवः ३ गणेशः<br>   १ विष्णुः<br>५ देवी  ४ रविः 	| ३ रविः<br>२ शिवः ३ गणेशः<br>    १ रविः<br>५ देवी  ४ विष्णुः 	| ४ द
आम् table एव
यथाकथञ्चित् नावगतं तन्मया क्षम्यताम्

2022-12-30 08:36 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +     इति पूजापङ्कजभास्करे ॥
Astu

2022-12-30 08:39 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +[^२]:
अस्तु

2022-12-30 08:40 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    इति शङ्खपूजाकर्तव्यपरम् ॥
सर्वत्र एवमेव कृतम् साधु वा इति एकवारं दृष्ट्वा वदति वा महोदय?

2022-12-30 08:40 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +     इति बालबोधे ।।
आम्

2022-12-30 08:41 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    इदं महाभिषेकफलपरम् ॥
अस्तु

2022-12-30 08:43 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +[^15]:
अस्तु

2022-12-30 08:44 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    इति शङ्खपूजाकर्तव्यपरम् ॥
23-तमा पादटिप्पनी सम्यङ् नास्ति। 

उद्धरणारम्भात् पूर्वं रिक्तापङ्क्तिर् भवेद् अपि सर्वत्र।

2022-12-30 08:45 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    | १ शिवः<br>२ विष्णुः ३ रविः<br>   १ शिवः<br>५ देवी  ४ गणेशः 	| २ विष्णुः<br>२ शिवः ३ गणेशः<br>   १ विष्णुः<br>५ देवी  ४ रविः 	| ३ रविः<br>२ शिवः ३ गणेशः<br>    १ रविः<br>५ देवी  ४ विष्णुः 	| ४ द
नावगतञ्चेत् प्रष्टव्यं ननु। https://www.tablesgenerator.com/markdown_tables इतस्य प्रयोगो ऽधिगतः टॆलिग्राम्य् उक्तः? किम् अस्पष्टम्?

2022-12-31 06:10 UTC, vvasuki requested changes
https://github.com/vishvAsa/vedAH_yajuH/pull/71 इत्यत्राद्यन्तम् परिशील्य उत्तररहितेषु दोषसूत्रेषु प्रतिस्पन्दताम्।

2022-12-31 06:10 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +     इति बालबोधे ।।
उद्धरणात् पूर्वं नाम आदिम->-चिह्नवत्-पङ्क्तेः पूर्वम्, न तु `[^7]:` इत्यादेः पूर्वम्।

2022-12-31 06:10 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    इदं महाभिषेकफलपरम् ॥
उद्धरणात् पूर्वं नाम आदिम->-चिह्नवत्-पङ्क्तेः पूर्वम्, न तु `[^7]:` इत्यादेः पूर्वम्।

2023-01-01 13:26 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    | १ शिवः<br>२ विष्णुः ३ रविः<br>   १ शिवः<br>५ देवी  ४ गणेशः 	| २ विष्णुः<br>२ शिवः ३ गणेशः<br>   १ विष्णुः<br>५ देवी  ४ रविः 	| ३ रविः<br>२ शिवः ३ गणेशः<br>    १ रविः<br>५ देवी  ४ विष्णुः 	| ४ द
आम्

2023-01-01 13:28 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    | १ शिवः<br>२ विष्णुः ३ रविः<br>   १ शिवः<br>५ देवी  ४ गणेशः 	| २ विष्णुः<br>२ शिवः ३ गणेशः<br>   १ विष्णुः<br>५ देवी  ४ रविः 	| ३ रविः<br>२ शिवः ३ गणेशः<br>    १ रविः<br>५ देवी  ४ विष्णुः 	| ४ द
![Screenshot_20230101-185717_Chrome](https://user-images.githubusercontent.com/105146383/210172227-93767754-3a03-4cf4-8936-6582caef05b5.jpg)


तस्मिन् एवं सम्यगेव दर्शयति, परन्तु लिंपने नागच्छति

2023-01-03 04:52 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    इति शङ्खपूजाकर्तव्यपरम् ॥
समीकृता

2023-01-03 04:53 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +     इति बालबोधे ।।
[^7]: इत्यादेः पूर्वं मास्तु वा रिक्तपङ्क्तिः?

2023-01-03 04:54 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +     इति बालबोधे ।।
पादटिप्पणीसंख्यापूर्व - रिक्तपंक्तिः मास्तु वा

2023-01-03 04:55 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    इदं महाभिषेकफलपरम् ॥
आम्

2023-01-03 05:44 UTC, vvasuki requested changes

2023-01-03 05:44 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +     इति बालबोधे ।।
तदपि भवत्व् एव। >-पङ्क्तेः पूर्वं नासीद् इति विवक्षितम्। अधुना सम्यग् अस्ति।

2023-01-03 05:44 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    | १ शिवः<br>२ विष्णुः ३ रविः<br>   १ शिवः<br>५ देवी  ४ गणेशः 	| २ विष्णुः<br>२ शिवः ३ गणेशः<br>   १ विष्णुः<br>५ देवी  ४ रविः 	| ३ रविः<br>२ शिवः ३ गणेशः<br>    १ रविः<br>५ देवी  ४ विष्णुः 	| ४ द
तत्र प्रयोग इमे दोषाः। 

- प्रथमपङ्क्तौ किमपि न स्यात्। स्तम्भशीर्षिकाणां कृते तत्। 
- द्वितीयपङ्क्तौ केवलं २ विष्णुः ३ रविः इत्यादि स्यात्। तृतीयपङ्क्तौ १ विष्णुर् इत्यादिकम्। ४-तम पङ्क्तौ च ५ देवीत्यादिकम्। एकस्याम् एव तालिका-पङ्क्तौ सर्वा अपि पङ्क्तयो न स्थापनीयाः। 

परिभाषा - स्तम्भो नाम table-column, पङ्क्तिर् नाम table row.

2023-01-03 05:45 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    | १ शिवः<br>२ विष्णुः ३ रविः<br>   १ शिवः<br>५ देवी  ४ गणेशः 	| २ विष्णुः<br>२ शिवः ३ गणेशः<br>   १ विष्णुः<br>५ देवी  ४ रविः 	| ३ रविः<br>२ शिवः ३ गणेशः<br>    १ रविः<br>५ देवी  ४ विष्णुः 	| ४ द
https://tableconvert.com/markdown-generator इत्यपि प्रयोक्तुं शक्यम्।

2023-01-04 14:24 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    | १ शिवः<br>२ विष्णुः ३ रविः<br>   १ शिवः<br>५ देवी  ४ गणेशः 	| २ विष्णुः<br>२ शिवः ३ गणेशः<br>   १ विष्णुः<br>५ देवी  ४ रविः 	| ३ रविः<br>२ शिवः ३ गणेशः<br>    १ रविः<br>५ देवी  ४ विष्णुः 	| ४ द
अस्तु महोदय प्रयतिष्ये

2023-01-06 16:47 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    | १ शिवः<br>२ विष्णुः ३ रविः<br>   १ शिवः<br>५ देवी  ४ गणेशः 	| २ विष्णुः<br>२ शिवः ३ गणेशः<br>   १ विष्णुः<br>५ देवी  ४ रविः 	| ३ रविः<br>२ शिवः ३ गणेशः<br>    १ रविः<br>५ देवी  ४ विष्णुः 	| ४ द
कृत्वा सूचयतु

2023-01-06 16:49 UTC, vvasuki requested changes
उक्ता दोषाः सर्वत्रास्यां सञ्चिकायां परिहार्या अन्विष्य।

2023-01-06 16:49 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    > देवोच्छिष्टं गृहीत्वा तु निर्माल्यभोजिने नमः ।
उद्धरणारम्भात् पूर्वं रिक्तापङ्क्तिर् अस्तु।

2023-01-06 16:49 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    > विष्वक्सेनोद्धवाक्रूराः सनकाद्या महर्षयः ।
उद्धरणारम्भात् पूर्वं रिक्तापङ्क्तिर् अस्तु।

2023-01-06 16:49 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    >
कुत एतत् चिह्नम् अत्र?

2023-01-06 16:49 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    > स्नाने धूपे प्रदीपे च नैवेद्योषः प्रबोधयोः ।
उद्धरणारम्भात् पूर्वं रिक्तापङ्क्तिर् अस्तु।

2023-01-06 16:49 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    > तद्वद्दीपं च नेत्रादिपादपर्यन्तयोगतः ।
उद्धरणारम्भात् पूर्वं रिक्तापङ्क्तिर् अस्तु।

2023-01-06 16:49 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    > सिताज्यमधुसम्मिश्रं गुग्गुल्वगरुचन्दनम् ।
उद्धरणारम्भात् पूर्वं रिक्तापङ्क्तिर् अस्तु।

2023-01-06 17:09 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    > सिताज्यमधुसम्मिश्रं गुग्गुल्वगरुचन्दनम् ।
अस्तु

2023-01-06 17:10 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    > स्नाने धूपे प्रदीपे च नैवेद्योषः प्रबोधयोः ।
अस्तु महोदय

2023-01-06 17:12 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    >
तत्र पृष्ट संख्या लेखन समये काचित् समस्या जाता अतः तत् चिह्नं स्थाप्य दृष्टं सम्यक् भवति वा इति, विस्मृतं निष्कासितुम्, सम्यक्करोमि

2023-01-06 17:12 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    > विष्वक्सेनोद्धवाक्रूराः सनकाद्या महर्षयः ।
अस्तु

2023-01-06 17:12 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    > देवोच्छिष्टं गृहीत्वा तु निर्माल्यभोजिने नमः ।
अस्तु

2023-01-06 17:13 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    | १ शिवः<br>२ विष्णुः ३ रविः<br>   १ शिवः<br>५ देवी  ४ गणेशः 	| २ विष्णुः<br>२ शिवः ३ गणेशः<br>   १ विष्णुः<br>५ देवी  ४ रविः 	| ३ रविः<br>२ शिवः ३ गणेशः<br>    १ रविः<br>५ देवी  ४ विष्णुः 	| ४ द
एवमेव करिष्यामि आचार्य!

2023-01-07 02:23 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    >
यथामति सूचितं सर्वं समीकृतमिति मन्ये

2023-01-07 02:42 UTC, vvasuki requested changes

2023-01-07 02:42 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    | १ शिवः<br>२ विष्णुः ३ रविः<br>   १ शिवः<br>५ देवी  ४ गणेशः 	| २ विष्णुः<br>२ शिवः ३ गणेशः<br>   १ विष्णुः<br>५ देवी  ४ रविः 	| ३ रविः<br>२ शिवः ३ गणेशः<br>    १ रविः<br>५ देवी  ४ विष्णुः 	| ४ द
एतन्न कृतं खलु - कृत्वैवेहोत्तरं लिखतु

2023-01-07 02:42 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    > विष्वक्सेनोद्धवाक्रूराः सनकाद्या महर्षयः ।
यथापूर्वम् एवास्ति।

2023-01-07 02:42 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    'क्षीरेण क्षीयते पापं दध्ना धनविवर्धनम् ।
अत्रोद्धरणचिह्नविन्यास इष्टो यथाऽन्यत्र कृतो भवत्या।

2023-01-07 02:42 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    'शालग्रामं त गण्डक्यां नर्मदायां शिवं तथा ।
`>`-चिह्नम् प्रयुङ्क्ताम्।

2023-01-07 02:42 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +अथ पुरुषसूक्तन्यासः ॥ ॐ सहस्रशीर्षा पुरुषः । सहस्राक्षः सहस्रपात् । स भूमिं विश्वतो वृत्वा । अत्ययतिष्ठद्दशाङ्गुलम् ॥ वामकराय नमः ॥ ॐ पुरुष एवेदं सर्वम् । यद्भूतं यच्च भव्यम् । उतामृतत्वस्येशानः । यद
सर्वत्र ०-चिह्नस्य स्थाने देवनागरीसङ्क्षेपचिह्नम् प्रयुञ्जीत - ॰ इति। वर्तते तयोर् भेदः। Find-replace-प्रयोगो वरस् स्यात्।

2023-01-07 02:42 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +अ०शुश्च मे रश्मिश्च मेऽदाभ्यश्च मेऽधिपतिश्च म उपा०शुश्च मेऽन्तर्यामश्च म ऐन्द्रवाय॒वश्च मे मैत्रावरुणश्च म आश्विनश्च मे प्रतिप्रस्थानश्च मे शुक्रश्च मे मन्थी च म आग्रयणश्च मे वैश्वदेवश्च मे ध्रुवश्च
कुतो ऽत्र मध्ये ०-चिह्नान्य् अनुस्वारस्य स्थाने??

2023-01-07 02:48 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    > विष्वक्सेनोद्धवाक्रूराः सनकाद्या महर्षयः ।
सामीकृतं

2023-01-07 03:02 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    'क्षीरेण क्षीयते पापं दध्ना धनविवर्धनम् ।
पञ्चामृत - पञ्चोदकस्नानद्वयोरपि विन्यासो एवं उक्ता रीत्या कृतः महोदय

2023-01-07 03:22 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    'क्षीरेण क्षीयते पापं दध्ना धनविवर्धनम् ।
ओह् - मया न लक्षितं स्यात्। अधस् तु सम्यक् कृतम्। तत्रापि पूर्वकृते परिष्करोतु - नाधिकश्रमाय स्यात्।

2023-01-07 10:31 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    'क्षीरेण क्षीयते पापं दध्ना धनविवर्धनम् ।
भवतः कथनानन्तरमेव कृतम्

2023-01-07 10:34 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    'शालग्रामं त गण्डक्यां नर्मदायां शिवं तथा ।
प्रयुङ्क्तं

2023-01-07 10:35 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +अ०शुश्च मे रश्मिश्च मेऽदाभ्यश्च मेऽधिपतिश्च म उपा०शुश्च मेऽन्तर्यामश्च म ऐन्द्रवाय॒वश्च मे मैत्रावरुणश्च म आश्विनश्च मे प्रतिप्रस्थानश्च मे शुक्रश्च मे मन्थी च म आग्रयणश्च मे वैश्वदेवश्च मे ध्रुवश्च
सः कश्चन प्रयोगः अस्ति खलु ग्ं इति उच्चारणे प्रायेण तदेव एवं लिखितम्

2023-01-08 09:54 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +अ०शुश्च मे रश्मिश्च मेऽदाभ्यश्च मेऽधिपतिश्च म उपा०शुश्च मेऽन्तर्यामश्च म ऐन्द्रवाय॒वश्च मे मैत्रावरुणश्च म आश्विनश्च मे प्रतिप्रस्थानश्च मे शुक्रश्च मे मन्थी च म आग्रयणश्च मे वैश्वदेवश्च मे ध्रुवश्च
hm - ँ-चिह्नम् प्रयुङ्क्तं तादृशे स्थले  - शून्यम् मास्तु।

2023-01-09 09:28 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +अ०शुश्च मे रश्मिश्च मेऽदाभ्यश्च मेऽधिपतिश्च म उपा०शुश्च मेऽन्तर्यामश्च म ऐन्द्रवाय॒वश्च मे मैत्रावरुणश्च म आश्विनश्च मे प्रतिप्रस्थानश्च मे शुक्रश्च मे मन्थी च म आग्रयणश्च मे वैश्वदेवश्च मे ध्रुवश्च
अनुसारम् एव लिखामि वा?

2023-01-09 09:31 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +अथ पुरुषसूक्तन्यासः ॥ ॐ सहस्रशीर्षा पुरुषः । सहस्राक्षः सहस्रपात् । स भूमिं विश्वतो वृत्वा । अत्ययतिष्ठद्दशाङ्गुलम् ॥ वामकराय नमः ॥ ॐ पुरुष एवेदं सर्वम् । यद्भूतं यच्च भव्यम् । उतामृतत्वस्येशानः । यद
Find replace कृते सति शून्यं यत्र यत्र अपेक्षितं तत्रापि इदमेव आयाति खलु?

2023-01-09 10:20 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +अ०शुश्च मे रश्मिश्च मेऽदाभ्यश्च मेऽधिपतिश्च म उपा०शुश्च मेऽन्तर्यामश्च म ऐन्द्रवाय॒वश्च मे मैत्रावरुणश्च म आश्विनश्च मे प्रतिप्रस्थानश्च मे शुक्रश्च मे मन्थी च म आग्रयणश्च मे वैश्वदेवश्च मे ध्रुवश्च
अनुस्वारमेव लिखितवती सद्यः

2023-01-09 14:25 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +अथ पुरुषसूक्तन्यासः ॥ ॐ सहस्रशीर्षा पुरुषः । सहस्राक्षः सहस्रपात् । स भूमिं विश्वतो वृत्वा । अत्ययतिष्ठद्दशाङ्गुलम् ॥ वामकराय नमः ॥ ॐ पुरुष एवेदं सर्वम् । यद्भूतं यच्च भव्यम् । उतामृतत्वस्येशानः । यद
Replace all इति कृते सा समस्या स्यात् - एकानन्तरम् एकम् इति क्रमेण परीक्ष्य परिवर्तनं शक्यम् एव।

2023-01-09 15:35 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +अथ पुरुषसूक्तन्यासः ॥ ॐ सहस्रशीर्षा पुरुषः । सहस्राक्षः सहस्रपात् । स भूमिं विश्वतो वृत्वा । अत्ययतिष्ठद्दशाङ्गुलम् ॥ वामकराय नमः ॥ ॐ पुरुष एवेदं सर्वम् । यद्भूतं यच्च भव्यम् । उतामृतत्वस्येशानः । यद
अस्तु

2023-01-10 01:50 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +अथ पुरुषसूक्तन्यासः ॥ ॐ सहस्रशीर्षा पुरुषः । सहस्राक्षः सहस्रपात् । स भूमिं विश्वतो वृत्वा । अत्ययतिष्ठद्दशाङ्गुलम् ॥ वामकराय नमः ॥ ॐ पुरुष एवेदं सर्वम् । यद्भूतं यच्च भव्यम् । उतामृतत्वस्येशानः । यद
कृत्वैव प्रतिवदेद् भवती। तेन भ्रमो वार्यते, स्पष्टता भवति।

2023-01-10 01:51 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +    {{< figure src="../images/panchamrita-maNDalam.jpg" title="" class="thumbnail">}}
एतदनुसारेण चित्रसञ्चिकानाम परिवर्तयतु panchamrita-maNDalam.jpg इति।

2023-01-10 05:42 UTC, vibhadiga commented on taittirIyam/sUtram/baudhAyanaH/brahma-karma-samuchchayaH/1_AhnikakANDam/15_sarvadevasAmAnyapUjA.md
> +अथ पुरुषसूक्तन्यासः ॥ ॐ सहस्रशीर्षा पुरुषः । सहस्राक्षः सहस्रपात् । स भूमिं विश्वतो वृत्वा । अत्ययतिष्ठद्दशाङ्गुलम् ॥ वामकराय नमः ॥ ॐ पुरुष एवेदं सर्वम् । यद्भूतं यच्च भव्यम् । उतामृतत्वस्येशानः । यद
कृतम्

2023-01-12 04:06 UTC, merged