First set of Mark down (1st Row of the table of content
vishvAsa/vedAH_yajuH pull request #94
Opened 2022-11-23 01:54 UTC by kssvasan

First set of Mark down (1st Row of the table of content

2022-11-23 03:24 UTC, vvasuki requested changes

2022-11-23 03:24 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/prayoga-ratna-mAlA/1_pUrvaH.md
> +## अग्निनिर्णय:
विसर्गचिह्नं स्यात्।

2022-11-23 03:24 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/prayoga-ratna-mAlA/1_pUrvaH.md
> +## नान्दीनिर्णय:
विसर्गचिह्नं स्यात्।

2022-11-23 03:24 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/prayoga-ratna-mAlA/1_pUrvaH.md
> +## नान्दीकाल:
विसर्गचिह्नं स्यात्।

2022-11-23 03:24 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/prayoga-ratna-mAlA/1_pUrvaH.md
> +## जीवत्पितृकनान्दीविषय:
विसर्गचिह्नं स्यात्।

2022-11-23 03:24 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/prayoga-ratna-mAlA/1_pUrvaH.md
> +## पुण्याहनिर्णय:
विसर्गचिह्नं स्यात्।

2022-11-23 03:24 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/prayoga-ratna-mAlA/1_pUrvaH.md
> +## नान्दीश्राद्धप्रयोग:
विसर्गचिह्नं स्यात्।

2022-11-23 06:35 UTC, kssvasan commented on taittirIyam/sUtram/baudhAyanaH/prayoga-ratna-mAlA/1_pUrvaH.md
> +## संस्कार निर्णय:
अस्तु | करिष्यामि | अन्ये सर्वे साधु वा?

2022-11-23 06:47 UTC, kssvasan reviewed
Corrected for the visargha symbol

2022-11-23 10:54 UTC, kssvasan commented on taittirIyam/sUtram/baudhAyanaH/prayoga-ratna-mAlA/1_pUrvaH.md
> +## अग्निनिर्णय:
विसर्गचिह्नं स्थापितवान् |

2022-11-23 10:55 UTC, kssvasan commented on taittirIyam/sUtram/baudhAyanaH/prayoga-ratna-mAlA/1_pUrvaH.md
> +## नान्दीकाल:
विसर्गचिह्नं स्थापितवान् |

2022-11-23 10:55 UTC, kssvasan commented on taittirIyam/sUtram/baudhAyanaH/prayoga-ratna-mAlA/1_pUrvaH.md
> +## जीवत्पितृकनान्दीविषय:
विसर्गचिह्नं स्थापितवान् |

2022-11-23 10:56 UTC, kssvasan commented on taittirIyam/sUtram/baudhAyanaH/prayoga-ratna-mAlA/1_pUrvaH.md
> +## पुण्याहनिर्णय:
विसर्गचिह्नं स्थापितवान् |

2022-11-23 11:36 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/prayoga-ratna-mAlA/1_pUrvaH.md
> +## संस्कार निर्णय:
कृत्वा ऽत्र कृतम् इति लिखतु। 
अन्यत्र समस्याऽस्ति चेद् यथास्थानं वदिष्यामि।

2022-11-23 17:32 UTC, kssvasan reviewed
Second row markdown till sarvakarma

2022-11-24 05:28 UTC, kssvasan commented on taittirIyam/sUtram/baudhAyanaH/prayoga-ratna-mAlA/1_pUrvaH.md
> +## संस्कार निर्णय:
विसर्ग चिह्नम् स्थापितवान् | संस्कारनिर्णय: -  रिक्तस्थानं अपाकृतवान् |

2022-11-24 05:30 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/prayoga-ratna-mAlA/1_pUrvaH.md
> +## प्रधानसङ्कल्प:
विसर्गः

2022-11-24 05:36 UTC, kssvasan commented on taittirIyam/sUtram/baudhAyanaH/prayoga-ratna-mAlA/1_pUrvaH.md
> +## प्रधानसङ्कल्प:
इदानिं विसर्ग चिह्नम् स्थापितवान् |

2022-11-26 18:15 UTC, kssvasan reviewed
Next set of markdown. till sthaalipakah.  Couldn't find item no 32 & 34 (from the vishaya suchi).

2022-11-27 01:05 UTC, vvasuki commented on taittirIyam/sUtram/baudhAyanaH/prayoga-ratna-mAlA/1_pUrvaH.md
> +## अग्निनाशनिमित्तानि
> Next set of markdown. till sthaalipakah. Couldn't find item no 32 

https://archive.org/details/baudhayanaprayogaratnamalaofvenkateshabhattatippanisuriramachandrasastrisirsipri/page/n10/mode/1up ityatrōktayā rītyā -

![image](https://user-images.githubusercontent.com/2664797/204114409-6a254be4-cd7d-4608-965b-9bf1d307ac56.png)

ityasti. ētad bhavatā sthāpitam ēva. kā samasyā tarhi?


> & 34 (from the vishaya suchi).

asya sthānē "yadi nadyuttaraṇe" ityasmāt pūrvam - 

```
## prāyaścittāntarāṇi
```
iti sthāpayatu.

2023-01-26 15:19 UTC, merged